### ISSUE TITLE
[Bug]: Revs can't invite people

### ISSUE THREAD

**Issue by LynxSolstice** [Aurorastation/Aurora.3#16950] opened 2023-07-31 06:52 UTC
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

![image](https://github.com/Aurorastation/Aurora.3/assets/112824777/6f622f7e-b083-43e6-a391-eaec18b2fc23)

### How to reproduce

Be rev, right click person, be unable to invite them to be a revolutionary

**Comment by scheveningensun** [comment] 2023-07-31 07:25
did you have a window panel button in this part of your screen labelled "Abilities" or anything like that? if not, then this is definitely a bug

**Comment by Doxxmedearly** [comment] 2023-07-31 11:46
This is a duplicate of #16727

**Closed** 2023-08-02 13:45 UTC
