### ISSUE TITLE
Suit Coolers do not cool down Industrial IPC's

### ISSUE THREAD

**Issue by Karakamenk** [Aurorastation/Aurora.3#13490] opened 2022-04-13 00:19 UTC
They reduce the rate down to a 10 kelvin per second gain on G2's. Barely any drain on the suit cooler battery.

**Comment by Ben10083** [comment] 2022-04-13 20:44
Duplicate of [#12164](https://github.com/Aurorastation/Aurora.3/issues/12164)

**Closed** 2022-05-11 00:11 UTC
