### ISSUE TITLE
Dionaea limb regeneration is instant for first dismemberment.

### ISSUE THREAD

**Issue by BurgerLUA** [Aurorastation/Aurora.3#5472] opened 2018-10-23 21:35 UTC
Got a roboticist to cut off my arm with a saw. It instantly regenerated as soon as they cut it off. The cooldown started after the second cut.

**Comment by Sindorman** [comment] 2018-10-23 23:43
Duplicate of #5418

**Closed by Sindorman** 2018-10-23 23:43 UTC
