### ISSUE TITLE
[Bug]: Large Disposal Units Instantly Suck You Into the Pipes

### ISSUE THREAD

**Issue by furrycactus** [Aurorastation/Aurora.3#19702] opened 2024-07-25 12:06 UTC
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The large Disposal Units that used to be commonplace before the smaller wall-mounted ones function like omni-directional delivery chutes, in addition to their normal functionality. If you push someone or something, or walk into them, you're immediately ejected down the disposals pipe network and into the trash compactor. Functions regardless of whether or not the pump is off or if the unit is pressurised, and is instantaneous with no chance of escape.

![image](https://github.com/user-attachments/assets/e0c35589-4710-4a3d-805f-394bf1a98587)

One of the culprits in question.

### How to reproduce

1. Locate a large Disposals Unit.
2. Walk onto the tile it occupies.
3. succ

### Round ID

cuS-aUd4

### Staff ckey

Melariara

**Comment by EJDenton** [comment] 2024-07-25 18:06
@furrycactus I wasn't able to replicate this. I tried various disposal bins, including the one shown in your report (the janitor closet I believe) and I'm unable to walk onto the bin. I can click and drag myself into it but the suction isn't instantaneous and seems to be operating as intended. If you can recheck your steps and see if it is still happening.

**Comment by listerla** [comment] 2024-07-25 21:24
I had this occur to me. I believe round ID is cuS-awuY

**Comment by Jasorn** [comment] 2024-07-25 22:56
I think https://github.com/Aurorastation/Aurora.3/pull/19624 might be causing it, since its test-merged rn, and it only seems to happen on live, so

**Comment by FluffyGhoster** [comment] 2024-07-26 04:15
Fixed in last commit, will be visible in game whenever the testmerge is refreshed

**Closed by FluffyGhoster** 2024-07-26 04:15 UTC
