### ISSUE TITLE
Dionae had Mouths removed in Baymerge.

### ISSUE THREAD

**Issue by SirFruitcakes** [Aurorastation/Aurora.3#1794] opened 2017-02-17 17:58 UTC
I don't think this is intentional, i've spoken to multiple coders and noone could explain why they don't have them anymore, or if they were removed and by who if so. I don't understand why it was removed, in both Mechanics and Lore it makes no sense. 

To explain, As a Nymph they can literally eat anything Organic, I understand why they have limits as a Worker (it would be BS if they could use Devour, or siphon large amounts of blood from people via gene sampling), but why wouldn't they be able to simply eat normal foods like people can? If you want to get technical, they would have 5 mouths, one on each limb... I understand why that can't be the case, too, but it's fine to just place a Mouth onto their head like before? 

I'm seriously convinced it was an oversight, because the removal/change serves no Mechanical purpose and was only really RP when it was used or a very minimal Mechanical help.

If i'm wrong here, just correct me with reasoning on why it was removed, if i'm not wrong, please fix! I really enjoyed being able to eat stuff to survive just a little longer in Darkness, or speed regrowth of limbs. I almost feel like the species is missing something that was frankly critical to the Atmosphere of it.

**Comment by LordFowl** [comment] 2017-02-17 19:42
_Working as intended_

**Comment by NanakoAC** [comment] 2017-02-23 19:33
This is not working as intended. Diona, even adult gestalts, have some mechanics based on food. They require large amounts of nutrition to regrow lost appendages, and while they can feed by absorbing gases, this is only possible in a pressurised area

**Comment by NanakoAC** [comment] 2017-03-04 00:06
An update: This is indeed a bug. It wasnt even intended behaviour in bay.

A screwup with typing hierarchies caused a runtime error with diona heads in the code that checks whether something has a mouth, defaulting to a negative value. Will be fixed in next patch

**Comment by NanakoAC** [comment] 2017-03-04 05:07
fixed in #1871

**Closed** 2017-03-22 16:23 UTC
Labels: bug:confirmed, flag:awaiting merge
