### ISSUE TITLE
Recent Change messed up office

### ISSUE THREAD

**Issue by Sprockevis** [Aurorastation/Aurora.3#13862] opened 2022-05-09 22:49 UTC
![image](https://user-images.githubusercontent.com/105250618/167510911-e2ac5be2-da95-4f73-aef7-8906300b311b.png)

Recent changes to Deck 3 I think caused some 'bleed in' from the Reps office. I can see but not use their door controls and lights, also can see the laptop through the wall. The most pressing thing though is the cork board on my offices' wall is now on my desk.

**Comment by SleepyGemmy** [comment] 2022-05-10 12:51
duplicate of #13828. i.e. code issue, not a mapping issue.

**Comment by SleepyGemmy** [comment] 2022-05-10 13:26
![image](https://user-images.githubusercontent.com/99297919/167639318-6e84ff6c-bb1a-4923-b408-01f70a65182c.png)

**Closed** 2022-05-11 00:10 UTC
