### ISSUE TITLE
Crime Scene Kit is Missing a row of slots.

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora.3#231] opened 2016-03-24 22:43 UTC
The CSI CSK is missing a row of slots, presumably lost in the patchcode rendition of new Forensic Tech, and thus an oversight of code transfer.

**Comment by SierraKomodo** [comment] 2016-03-31 09:05
Confirmed. On top of this, while it shows you 7 slots, the CSI kit will tell you it's full when only 6 of those 7 slots are in use.

**Comment by NanakoAC** [comment] 2016-08-04 18:59
Fixed in next patch by #665 , i didn't notice this issue before it got merged.

The problem was, although the number of slots was increased, the total capacity wasn't increased appropriately, which makes for some screwy behaviour

**Closed** 2016-08-04 19:02 UTC
Labels: bug:confirmed, flag:awaiting merge, flag:duplicate
