### ISSUE TITLE
Reagents in blood sometimes duplicate in value

### ISSUE THREAD

**Issue by FlamingLily** [Aurorastation/Aurora.3#15471] opened 2022-12-30 06:22 UTC
Game ID: clD-aF20
Played Character: Mira Tilton (Had the bug happen to), Ayah Nasri (Identified the bug)

Sometimes, for reasons I don't know, reagents in one's blood will amplify in value (The values pictured are far greater than the values that would be injected)
https://cdn.discordapp.com/attachments/951240371885735946/1058264421543182438/image.png

**Comment by SleepyGemmy** [comment] 2022-12-30 14:24
duplicate of #11156.

**Comment by FlamingLily** [comment] 2022-12-31 03:53
> duplicate of #11156.

No sleeper or IV on drain mode was used, I don't think it's the same issue.

**Comment by SleepyGemmy** [comment] 2022-12-31 18:24
related to #11156.

**Comment by FluffyGhoster** [comment] 2023-09-10 06:10
Closing this in favor of #15471
If it turns out to not be the same issue, feel free to re-open / re-submit it once that one is marked as fixed

**Comment by SleepyGemmy** [comment] 2023-09-13 19:17
> Closing this in favor of #15471 If it turns out to not be the same issue, feel free to re-open / re-submit it once that one is marked as fixed

you linked the same issue.

**Comment by FluffyGhoster** [comment] 2023-09-13 19:58
Yea sorry, I meant to link #15804

**Closed** 2023-09-14 04:23 UTC
Labels: ✔️ Issue Replicable
