### ISSUE TITLE
Cannot Shoot Turrets?

### ISSUE THREAD

**Issue by Fortport** [Aurorastation/Aurora.3#5107] opened 2018-08-07 12:23 UTC
I went into the ai core and was gunned down. While I was being shot, I pulled my pistol and had it on lethal while it was fully charged. I clicked the turret repeatedly, but it didn't fire despite having no preferences for safety at all. I know this for a fact because I gunned down a spider not fifteen minutes before.

Eventually, I died after switching over to my baton and whacking the turret with it. What gives?

**Comment by Arrow768** [comment] 2018-08-07 20:14
Unable to reproduce.
Do you have a roundid ?

**Comment by Fortport** [comment] 2018-08-08 18:53
Afraid not. I am sorry.

**Comment by Arrow768** [comment] 2018-08-08 19:36
Closing it then

**Closed by Arrow768** 2018-08-08 19:36 UTC
Labels: Cannot Replicate
