### ISSUE TITLE
Shells no longer show their 'gender' when inspected.

### ISSUE THREAD

**Issue by ToasterStrudes** [Aurorastation/Aurora.3#6093] opened 2019-02-25 02:28 UTC
As stated in title, shells for a while were made to show genders due to them looking human, not sure if it was an intended change or a bug due to some recent change.

**Comment by dragoslava** [comment] 2019-02-25 02:31
https://github.com/Aurorastation/Aurora.3/issues/6082

Dupe of this

**Closed by dragoslava** 2019-02-25 02:31 UTC
Labels: Duplicate
