### ISSUE TITLE
Custom borg sprites not loading sometimes. In reference to #9530

### ISSUE THREAD

**Issue by StationCrab** [Aurorastation/Aurora.3#9565] opened 2020-08-01 19:31 UTC
At round start, when name is selected, an error pops up regarding custom sprites some of the time.

The error looks like this: 
![image](https://user-images.githubusercontent.com/45498074/89107934-8c793c00-d402-11ea-9f11-00c84bda1721.png)

Upon selecting a module, a similar error appears in reference to that module's sprite: 
![image](https://user-images.githubusercontent.com/45498074/89107941-a0bd3900-d402-11ea-871a-322577161c7d.png)

This only happens in a random fashion, sometimes the sprite will work at round start, but when a module reset is provided the error appears mid round. Some rounds it never appears at all, but I have heard reports in LOOC that the custom sprite is invisible to others, and relogging fixes it, I am unsure if these two issues are related.

I am posting this now in reference to PR #9530 

This is all the information I have at this time.

**Comment by JohnWildkins** [comment] 2020-12-06 09:36
Appears to be a duplicate of #8480

**Closed by JohnWildkins** 2020-12-06 09:36 UTC
