### ISSUE TITLE
Microphone circuit not doing anything.

### ISSUE THREAD

**Issue by Yonnimer** [Aurorastation/Aurora.3#8708] opened 2020-04-21 03:06 UTC
The microphone circuit from circuit printers is no longer doing anything, at all. Nothing is outputted or written when someone speaks.

**Comment by niennab** [comment] 2020-04-21 13:58
The universal recording isn't receiving any input as well. Perhaps related?

**Comment by runecap** [comment] 2020-04-23 01:48
To add, the microphone circuit seems to work inside circuit jumpsuits- but not inside implant assemblies.

**Comment by runecap** [comment] 2020-05-06 17:55
Looks like this was shadow-fixed, should close the issue.

**Comment by Alberyk** [comment] 2020-05-06 19:16
This was caused by a byond version issue.

**Closed by Alberyk** 2020-05-06 19:16 UTC
