### ISSUE TITLE
Intrepid's Cameras

### ISSUE THREAD

**Issue by stobarico** [Aurorastation/Aurora.3#13726] opened 2022-04-29 22:24 UTC
You can see Intrepid's cameras even when they are off-ship and far away. No clue how you'd be able to fix this tbh, considering I know very little how camera networks work in code.

**Comment by Ben10083** [comment] 2022-04-30 01:00
Duplicate of https://github.com/Aurorastation/Aurora.3/issues/13439

**Closed** 2022-05-15 13:58 UTC
