### ISSUE TITLE
Carps are broken

### ISSUE THREAD

**Issue by LeiteQualhado** [Aurorastation/Aurora.3#15850] opened 2023-02-17 14:27 UTC
Carps will attack the window even if they don't have line of sight with the person on the other side, which leads to the window breaking while shutters are down

Besides that, carps are attacking windows absurdly fast and breaching them in mere seconds

**Comment by SleepyGemmy** [comment] 2023-02-17 15:29
duplicate of #15621.

**Closed by SleepyGemmy** 2023-02-17 15:29 UTC
