### ISSUE TITLE
[Bug]: Stuck in overmap Z-level when lost in space.

### ISSUE THREAD

**Issue by Dahbunny** [Aurorastation/Aurora.3#16354] opened 2023-05-16 10:18 UTC
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Event / Other

### Describe the issue

When being thrown into space, you no longer "tumble" across multiple Z-levels, eventually arriving at locations, instead, you end up stuck on the Z-plane that hosts the overmap on the bottom left, and your unable to leave, as the map edges are solid, possible solution would be removing that z-plane from the space map edge scroll destinations?

### How to reproduce

Simply take any vessel to space, and cross the border on the edges.

**Comment by FluffyGhoster** [comment] 2023-11-17 13:18
Duplicate of #15669

**Closed by FluffyGhoster** 2023-11-17 13:18 UTC
