### ISSUE TITLE
Storage will remove a character sometimes and not open their job slot.

### ISSUE THREAD

**Issue by Chada-1** [Aurorastation/Aurora.3#2073] opened 2017-04-11 19:10 UTC
Cryogenic Storage and Robotic Storage will occasionally remove someone and not open their slot.  I've been told by Sierra Komodo that this has been a bug for a very long time, and is far from new.
I've only been a victim of it once, but if I am again, i'll take a screenshot or whatever if I need to. I only learned there weren't two Cyborgs in the said round at the very end, and was told to make this issue when another player had the same problem, but with Security Officer instead of Cyborg.

What should happen is simple, the character should cycle into Storage and the slot should be freed up, what happens is they occasionally get removed from the round, and the job slot goes into a permanent limbo unless an Admin forces it open.

I haven't tried reproducing the issue, but it seems like a very difficult one to reproduce anyhow, and it seems to work fine most of the time.

This is a rare but re-occuring issue.

**Comment by MarinaGryphon** [comment] 2017-04-11 21:24
What job, specifically? Were you using an alt title? That shouldn't cause an issue, but who knows.
(Wait, sec officers don't have alt titles. Please ignore.)

**Comment by MarinaGryphon** [comment] 2017-04-11 21:33
Next time you get this, PLEASE provide the game ID. It's invaluable.

**Comment by TrickingTrapster** [comment] 2017-04-11 21:45
I do believe it >might< be related to the person wearing their ID or not.

**Comment by Lohikar** [comment] 2017-04-11 21:46
Nope, cryo does not read ID card for job. Based off of an internal mind object.

**Comment by TrickingTrapster** [comment] 2017-04-11 21:47
Cryo doesn't, but if the ID card still exists, doesn't the person still show up on the manifest?

**Comment by Lohikar** [comment] 2017-04-11 21:48
I don't think so, cryo directly modifies records when someone is moved to long-term (which is also why #833 is possible).

Likely somehow someone's job or mind is becoming null, although I am not sure how that would happen normally.

**Comment by TrickingTrapster** [comment] 2017-04-11 21:50
And there isn't an updater that checks for ID cards and just writes the person back into the records? Just brainstorming here, I don't know the code.

**Comment by FirinMaLazors** [comment] 2020-09-14 05:09
Here is the code (in DespawnMob) that handles clearing records and manifests and freeing up jobs:
	if (H.mind)
		var/job = H.mind.assigned_role

		FreeRole(job)

		if(H.mind.objectives.len)
			qdel(H.mind.objectives)
			H.mind.special_role = null

	// Delete them from datacore.

	SSrecords.remove_record_by_field("name", H.real_name)
	SSrecords.reset_manifest()

There's a number of things that *look* like they could definitely mess up this process.  For instance, a wizard's apprentice contract overwrites the assigned_role of the apprentice, so if they cryo, their original job slot doesn't get freed.  Look for "assigned_role = " and "mind = " in Visual Basic to see what I see.  Having a schizo's alternate personality be in control while cryoing might also mess it up.  Also maybe if real_name gets messed with somehow (borer?  schizo?).

That said, this is all speculation.  I don't see any reports about this past 2017, so I guess the issue could either be kept open or closed.  It's definitely a "cold case" type of deal.

**Comment by WickedCybs** [comment] 2020-10-05 23:02
It is still an issue. Will grab a game ID when I notice it happens again. From my minor observations it happens the most when all slots are filled but one person cryos afterward.

**Comment by Amunak** [comment] 2020-11-25 19:20
As part of #10470 I [changed](https://github.com/Aurorastation/Aurora.3/pull/10470/files#diff-b870d52b3eae639ad2a5b8034d4fd73980da9cb1e677d0dd3d6f414f62637704R120-R125) how `FreeRole()` works. Are you absolutely sure that the issue here is with the names being the same? Because FreeRole was garbage and didn't actually free roles before unless it was the last slot for it, so it's possible at least part of the problem is now fixed.

**Comment by JohnWildkins** [comment] 2020-12-05 13:19
Doesn't appear to be an issue anymore, fixed in #10470.

**Closed by JohnWildkins** 2020-12-05 13:19 UTC
Labels: Cannot Replicate
