### ISSUE TITLE
Flipping digital eyepatches doesn't move the color dot around.

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#6300] opened 2019-04-13 05:41 UTC
![image](https://user-images.githubusercontent.com/19973802/56075228-423a0900-5e13-11e9-9eba-4a9757742ca4.png)
![image](https://user-images.githubusercontent.com/19973802/56075229-45cd9000-5e13-11e9-8269-b4803930344a.png)
Whoops

**Comment by JohnWildkins** [comment] 2020-12-06 13:33
duplicate of #4606

**Closed by JohnWildkins** 2020-12-06 13:33 UTC
