### ISSUE TITLE
AI players crash whenever there are explosions or depressurized areas on station

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#660] opened 2016-08-01 23:25 UTC
After seeing this reported in OOC several times, and experiencing it myself, I've identified a possible common thing between each case of AI's crashing on moving/jumping to AI core/jumping to another player - The station is always experiencing air alarms/pressure loss due to explosions or other issues (And I'm referring to multiple alarm levels of pressure loss, not a single room has a broken window).

Will probably need further investigation to confirm or debunk this as the cause (Or one of the causes), but it's something.

**Comment by SierraKomodo** [comment] 2016-08-01 23:33
Okay so in an event where we had an AI with this problem, we did have multiple atmos and camera alarms. Atmos alarms were cleared, camera alarms still exist, the AI is still crashing.

**Comment by SierraKomodo** [comment] 2016-08-01 23:41
During this same round, the AI stopped having crashing issues after the CT shuttle left the station. This is also after about half of the remaining camera alarms were cleared (There's a total of 10 alarms right now, 5 camera and 5 power). The crashing may have stopped from lowered population on station or lowered alerts, not sure which.

**Comment by BinaryEvolved** [comment] 2016-08-01 23:41
Interesting enough the issue did not occur for the first minute or so I was playing the AI, however directly after that any attempt to jump to any entity (other than clicking an alert on the alert console) would instantly caused a crash.

Here is a list of all the included alerts at the time: http://puu.sh/qmxTL/af1578524d.png

Here is a list of all the included alerts after for whatever reason the crash stopped occuring: http://puu.sh/qmyfw/05dc407b70.png

**Comment by skull132** [comment] 2016-08-02 00:24
I'm going to assume that this also happens when you don't have the alarm window open, ergo, it's not explicitly NanoUI related?

**Comment by BinaryEvolved** [comment] 2016-08-02 00:34
@skull132 That is correct, I tried this with multiple interfaces opened, and even after I completely restarted Byond, the crash still occurred.

**Comment by SierraKomodo** [comment] 2016-08-02 03:31
@skull132 In my past experiences with this bug, that is correct. Additionally, when it happens to me it randomly crashes when jumping to another player, jumping to the AI core, or just when moving around in general. The crashing immediately stops if I ghost or wipe-core. I haven't personally had a situation where the alerts go away before I give up on playing AI for the round and ghost.

**Comment by NanakoAC** [comment] 2016-08-03 05:31
@SierraKomodo Can you do me a favour.

Play security, get a laptop, and play around with the camera program on it.

Do you have any issues rapidly jumping between cameras on a laptop?

**Comment by SierraKomodo** [comment] 2016-08-20 05:12
Okay I have confirmed after three separate rounds that clearing all the alerts does not stop the AI from crashing. Additionally, even if you wipe core and another player takes the AI slot, they will continue to have the crashing issue as well until the server restarts. This is a game-breaking bug for the AI as anytime something starts going down, the AI becomes utterly gimped by the constant crashing.

**Comment by SierraKomodo** [comment] 2016-08-20 05:13
@NanakoAC I haven't had any issues using the security cameras on a laptop.

**Comment by LiquidRecluse** [comment] 2016-08-20 06:03
I can confirm that this has happened to me as A.I as well, mostly tracking people and announcements (I.E space dust.)

**Comment by AgentWhatever** [comment] 2016-08-24 07:41
Probably related to skulls comment in #726

**Comment by EJDenton** [comment] 2016-08-27 05:12
I was asked by Sierra to post my recent experience.

While playing AI I received the following suggestion from Nadrew.

Turn off Hardware Rendering. To do this:
Right click the title bar of the byond window when the game is open.
Open the client option, then preferences.
Uncheck "Use Graphics hardware for displaying maps"

My issue was that the client would hang to where I would have to close it after I tracked someone or jumped to a new camera. After disabling hardware rendering the situation seemed to improve although I would still hang from time to time.

At Nadrew's suggestion I will be updating my graphics drivers and seeing how things go.

**Comment by LadyFowls** [comment] 2019-10-11 03:22
This shouldnt be happening anymore since the new byond update, if it persists we can look into it

**Closed by LadyFowls** 2019-10-11 03:22 UTC
Labels: Bug Confirmed, Won't Fix
