### ISSUE TITLE
[NBT] Intrepid and Mining Shuttle Is Covered by the Horizon's Shields

### ISSUE THREAD

**Issue by SleepyGemmy** [Aurorastation/Aurora.3#13346] opened 2022-03-07 03:22 UTC
![image21](https://user-images.githubusercontent.com/99297919/156962259-c48327bf-38ba-4a80-af6f-87b5d7e1a601.png)
![image22](https://user-images.githubusercontent.com/99297919/156963327-18061fd1-766d-48a2-917b-d2dc1cdc6cce.png)

**Comment by mikomyazaki** [comment] 2022-03-07 13:39
Duplicate of #13156 will be fixed by #13316 anyway.

**Closed by mikomyazaki** 2022-03-07 13:39 UTC
