### ISSUE TITLE
Inventory tweaks

### ISSUE THREAD

**Issue by HetNeSS** [Aurorastation/Aurora.3#3206] opened 2017-08-01 18:31 UTC
Entering an arrivals shuttle with an atmospherics winter coat at your backpack duplicates it inside a personal posessions box.

**Comment by SoundScopes** [comment] 2017-08-01 20:28
Probably related & or duplicate report #3165

**Comment by Lohikar** [comment] 2017-08-01 20:31
Duplicate of #3165.

**Closed by Lohikar** 2017-08-01 20:31 UTC
Labels: flag:duplicate
