### ISSUE TITLE
Robotech vendor shows everything as 'null'.

### ISSUE THREAD

**Issue by Juani2400** [Aurorastation/Aurora.3#4174] opened 2018-01-28 00:08 UTC
As title says:

![imagen](https://user-images.githubusercontent.com/6277887/35477634-4645bb02-03bf-11e8-8c42-4314ef1d405a.png)

**Comment by skull132** [comment] 2018-01-28 00:09
Dupe of #4164

**Closed by skull132** 2018-01-28 00:09 UTC
