### ISSUE TITLE
It is not possible to deconstruct reinforced walls

### ISSUE THREAD

**Issue by streex321** [Aurorastation/Aurora.3#14137] opened 2022-05-29 02:12 UTC
There has been an issue with deconstructing reinforced walls in the five rounds I have attempted to do so. Everything works fine until the second time you have to use a welder, where it will cycle the action of cutting the struts but when the cycle finishes nothing happens, and utilizing the welder again comes up with the same results, stopping you from moving on.

**Comment by Doxxmedearly** [comment] 2022-05-29 15:10
Duplicate of #14108
Possibly related to the use_tool proc port from TG

**Closed** 2022-05-30 14:38 UTC
