### ISSUE TITLE
Cyborg Storage unity is invisible when there is a cyborg inside of it.

### ISSUE THREAD

**Issue by Sindorman** [Aurorastation/Aurora.3#15026] opened 2022-11-05 05:38 UTC
When I entered cyborg storage to log off, the storage unit disappeared until it processed and reset back to empty. I have not tried to reproduce it. But it probably is reproducible.

**Comment by SleepyGemmy** [comment] 2022-11-05 17:12
duplicate of #14989.

**Closed** 2022-11-05 17:12 UTC
Labels: Duplicate
