### ISSUE TITLE
Nymphs start with basic, and not rootsong

### ISSUE THREAD

**Issue by Yonnimer** [Aurorastation/Aurora.3#6142] opened 2019-03-13 00:52 UTC
What the title says. Nymphs spawn with basic and not rootsong.

**Comment by LordFowl** [comment] 2019-03-15 01:15
Duplicate of https://github.com/Aurorastation/Aurora.3/issues/6142

**Comment by Sindorman** [comment] 2019-03-15 01:27
@LordFowl you just referenced this  issue. Update reference please

**Closed** 2019-05-16 19:37 UTC
