### ISSUE TITLE
Combat cyborgs don't recharge their guns in cyborg rechargers

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#3573] opened 2017-10-04 04:38 UTC
Yes I've tried all of the possible methods, it doesn't recharge at all.

**Comment by Arrow768** [comment] 2017-10-04 17:45
The issue checklist is there to be completed before posting a issue.
Please dont just delete it.

Duplicate of #3550

**Comment by Lohikar** [comment] 2017-10-04 17:46
Not a duplicate.

**Closed** 2017-10-04 17:52 UTC
