### ISSUE TITLE
Can't interact with camera monitors while buckled. 

### ISSUE THREAD

**Issue by verywhiterabit** [Aurorastation/Aurora.3#2246] opened 2017-05-13 21:17 UTC
Mostly an issue with the detective's office as you can't actually use the camera monitor without unbuckling from your chair. Worked fine on the old map but they used office chairs, might make a difference what kind of chair it is but I'm not sure.

**Comment by LordFowl** [comment] 2017-05-13 21:35
Don't see how this could be a new map issue.

**Comment by skull132** [comment] 2017-05-14 00:08
It iiiis.

Office chairs have `buckle_movable = 1` set on them. This allows you to fuck around with computers while in them, I do believe. Regular chairs do not.

**Comment by LordFowl** [comment] 2017-05-14 00:14
That sounds like just a regular issue with chairs, not an issue caused by the new map.

**Comment by verywhiterabit** [comment] 2017-05-14 00:50
It was an issue that only came up with the new map, before I believe every chair setup next to a console was an office chair. Detective's office in the new map makes this issue stand out much more prominently. But yes, the actual issue isn't a new map thing.

**Comment by skull132** [comment] 2017-05-14 10:26
@LordFowl It's an implementation issue that should be fixed.

Changing that 1 variable for all chairs 5ever is out of the question. So either change the chairs in the new map to be office chairs, or modify the instances of those specific chairs to allow buckle_movable.

**Comment by LordFowl** [comment] 2017-05-14 13:51
I disagree. Just sitting in a chair should not disallow you from using a computer, regardless of the chair type. It strikes me as an issue with hiw they're coded.

**Comment by skull132** [comment] 2017-05-15 20:33
The code isn't changing, unfortunately.

Setting that var to 1 would lead to annoying shenanigans with buckling, such as prisoners being able to touch things and so forth. It's worked thus far, quite intuitively and normally. So the mechanic is obviously applied properly.

Just flip the boolean on local instances or swap the chairs, and done.

**Comment by LordFowl** [comment] 2017-05-17 13:31
I am rather questionable on how you would ever define that as intuitive and normative.

**Closed** 2022-04-14 23:27 UTC
Labels: Bug Confirmed, Development
