### ISSUE TITLE
Hostile mobs have wallhacks

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#15747] opened 2023-02-06 04:43 UTC
Their sight isn't blocked by obstacles and they rapidly attack windows between them and a potential target even if they never sighted them previously. The attacks also happen at a far increased rate, at least two per second seems like.

This is especially getting bad with carp since that leads to a lot of broken windows.

**Comment by SleepyGemmy** [comment] 2023-02-06 20:54
duplicate of #15621.

**Closed by SleepyGemmy** 2023-02-06 20:54 UTC
