### ISSUE TITLE
[Bug]: Chat Client and Warrant Assistant do not update the window when new data is sent

### ISSUE THREAD

**Issue by EJDenton** [Aurorastation/Aurora.3#16527] opened 2023-06-26 02:05 UTC
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

After creating or editing a warrant, clicking save or delete does not update the screen. I have to close out of the console window and open the console again to see the changes.

**Comment by NonQueueingMatt** [comment] 2023-06-26 13:35
This is tricky. Not sure why it happens. Might take a bit to fix.

**Comment by NonQueueingMatt** [comment] 2023-06-27 16:42
Chat client not updating is fixed in the next UI - was caused by React not recognising a state change if it's an object inside an object that changes (in this case, a string array in a custom type)

**Comment by NonQueueingMatt** [comment] 2023-06-27 18:48
fixed warraant assitant too

**Closed by NonQueueingMatt** 2023-06-27 18:48 UTC
