### ISSUE TITLE
Borg improperly slaved to Malf AI (or any AI)

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#206] opened 2016-03-03 18:45 UTC
#### Brief description of the issue

During rounds as a malfunctioning AI, borgs to not properly sync up or slave under certain conditions.

#### What you expected to happen

All borg that are generated on the station when an AI is present should be automatically slaved to the AI.

#### What actually happened

If a borg joins the round after it starts, they are not by default slaved to the AI or lawsynced.  Even if they are then linked to the AI, their laws do not sync up as part of this process, making them useless for the purposes of Malfuction AIs.  The only times borg are properly slaved and lawed with malfunction laws is if they spawn on the station at round start, or are built in-station.

#### Steps to reproduce
See above.

**Comment by skull132** [comment] 2016-03-03 23:05
Duplicate of #144 .

Fix pushed onto the live server today.

**Closed by skull132** 2016-03-03 23:05 UTC
Labels: Invalid
