### ISSUE TITLE
Station Alert consoles don't show alerts 

### ISSUE THREAD

**Issue by Juani2400** [Aurorastation/Aurora.3#1521] opened 2017-01-12 00:20 UTC
When clicking a station alert console (the one at the Engineering desk), they don't show a list of the current alerts. It just pops up an empty window.

**Comment by Lohikar** [comment] 2017-01-12 00:37
Does it show the headers for each alert type?

**Comment by Juani2400** [comment] 2017-01-12 00:48
Nope! It's empty. It only shows the header title at the top.

**Comment by skull132** [comment] 2017-03-05 13:13
Duplicate of #1839

**Closed by skull132** 2017-03-05 13:13 UTC
Labels: bug:confirmed
