### ISSUE TITLE
Some actions stopped appearing in log, even after relogging.

### ISSUE THREAD

**Issue by Komotez** [Aurorastation/Aurora.3#3046] opened 2017-07-15 21:11 UTC
Mid-round the logs that usually show the actions of splashing slimes with water ie:

"you splash x slime with water"
"x slimes sizzles from the water"

Suddenly stopped showing, the issue seems to be limited to actions regarding the beaker of water and slimes, as logs for filling the beaker or emptying the beaker on the floor show just fine.

Not a gamebreaking problem for me, just making it known here as per mod suggestion

**Comment by skull132** [comment] 2017-07-15 21:13
Fixed in dev.

Null entry got into the mob list. Also a dupe of somewhere, I'm sure.

**Closed** 2017-07-15 21:13 UTC
