### ISSUE TITLE
Elevator closing and Atomsmasher

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#13703] opened 2022-04-27 22:07 UTC
It's back babyyyyy
at around 2:19 into the round I tried to step onto the elevator when the doors closed on me, I was on the outer set of doors when they closed and stepped into the inner set when the elevator went up, what should be happening is me beeing inside the door of the elevator as it goes up, what is happening is that the doors and the floor move up and I remain on the ground floor on new floor tiles.

Round ID chE-c87T
I informed Peppermint96 about this and he was there for it.

**Comment by SleepyGemmy** [comment] 2022-10-19 19:19
duplicate of #12764.

**Closed** 2022-10-19 19:20 UTC
Labels: Duplicate
