### ISSUE TITLE
[Bug]: Crowbaring off then placing down full floor tiles places small ones instead.

### ISSUE THREAD

**Issue by Stev-the-third** [Aurorastation/Aurora.3#17149] opened 2023-08-26 12:27 UTC
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

If you crowbar up a full steel floor tile (Untested for other times), placing it back down cuases it to be the smaller 4 tiles.

**Comment by SleepyGemmy** [comment] 2023-08-26 15:33
duplicate of #14658. please search before creating an issue.

**Closed** 2023-08-26 15:33 UTC
Labels: Duplicate
