### ISSUE TITLE
[Bug]: Lobby/ghost crew manifest bluescreens

### ISSUE THREAD

**Issue by Greenjoe12345** [Aurorastation/Aurora.3#17640] opened 2023-10-20 02:55 UTC
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

 TypeError: Unable to get property 'toLowerCase' of undefined or null reference
   at Anonymous function (http://127.0.0.1:61031/tmp10764/tgui.bundle.js:1:759257)
   at Anonymous function (http://127.0.0.1:61031/tmp10764/tgui.bundle.js:1:41113)
   at map (http://127.0.0.1:61031/tmp10764/tgui.bundle.js:1:90914)
   at Anonymous function (http://127.0.0.1:61031/tmp10764/tgui.bundle.js:1:759027)
   at Anonymous function (http://127.0.0.1:61031/tmp10764/tgui.bundle.js:1:41113)
   at map (http://127.0.0.1:61031/tmp10764/tgui.bundle.js:1:90914)
   at t.ManifestSection (http://127.0.0.1:61031/tmp10764/tgui.bundle.js:1:758873)
   at Be (http://127.0.0.1:61031/tmp10764/tgui.bundle.js:1:174408)
   at Anonymous function (http://127.0.0.1:61031/tmp10764/tgui.bundle.js:1:174676)
   at Te (http://127.0.0.1:61031/tmp10764/tgui.bundle.js:1:174654)

**Comment by FluffyGhoster** [comment] 2023-10-20 06:03
Duplicate of #17615

**Closed by FluffyGhoster** 2023-10-20 06:03 UTC
Labels: 📄 Issue Duplicate
