### ISSUE TITLE
[Newmap] BYOND Crashes on compile in some cases

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#2902] opened 2017-07-02 03:13 UTC
Map `maps\aurora-2\aurora-7_derelict.dmm` causes BYOND on Linux to crash, and BYOND on Windows to behave strangely.

Unincluding this map fixes it.

**Comment by Alberyk** [comment] 2017-07-02 03:16
Also, the map seems to be broken even when running on windows, as you can't jump or teleport to the derelict

**Comment by skull132** [comment] 2017-07-02 11:36
Fixed in #2913 .

Might have been caused by me running TGM merge twice.

**Closed by skull132** 2017-07-02 11:36 UTC
Labels: flag:development, flag:high priority
