### ISSUE TITLE
Disposals maintenance belt does not work

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#295] opened 2016-05-15 10:41 UTC
All trash goes to the disposals office m where its spat out onto a straight conveyor belt. Once it's sorted and poked through, cargo techs throw a lever to start the belt, which pushes it onto another straight belt which is at a right angle to it. And then that belt takes it through the pipes, towards the final destination. This all works fine.

The last stop on its journey though, is the disposals maintenance, which is right between cargo and arrivals. IT's here that trash is supposed to be fed through the system onto the mass driver and spat out into space. There's only one belt here, one long continuous belt which turns a corner. Unfortunately this is broken.

Trash moving along the belt, cannot turn the corner, it gets stuck there. And so the whole disposals system is inevitably broken.

There are two ways to solve this issue:
1. Fix conveyor belts, so that a belt which turns a corner actually works, and doesnt get stuck. 
Or
2. Convert that last belt, into two straight belts that feed onto each other, the same way it's done in cargo.

First solution is best, but probably most difficult. Either works

**Comment by Arrow768** [comment] 2016-05-22 15:48
Duplicate of #247

**Closed** 2016-07-09 22:13 UTC
Labels: bug:confirmed
