### ISSUE TITLE
Annoying pAI bugs.

### ISSUE THREAD

**Issue by Chen-Yakumo** [Aurorastation/Aurora.3#6015] opened 2019-02-02 04:29 UTC
Checklist before you submit an issue! Feel free to partially or fully delete this in your eventual report.
* Do a quick key word search of the git for duplicate reports. If you find any, simply post a reply onto that issue instead!: N/A
* Please be specific in your description of the issue. Explain the desired result (what should be happening) and the actual result (what is happening). Simply stating that [something happens] is not very helpful at describing what's wrong. Multiple bugs around pAIs that make playing them a pain. Primarily as follows.

- Collapsing your chassis causes you to leave a second chassis behind, while remaining in mobile form. Collapsing your chassis a second time causes your mobile form to vanish, and return you to the card you left behind.
- Downloading and using the Crew Manifest does not show the Crew Manifest. Instead, you're greeted with a pop up window declaring "Initializing..." until the end of time, or the round, or the window is closed. Whichever comes first.
- The Digital Messenger is unable to send the majority of messages. I'm unable to produce exactly WHY it can't send them, but it randomly cuts in and out of being able TO send them. Receiving messages is, strangely, unaffected, resulting in a pAI who can receive messages but be unable to reply for no discernible reason.

* Have you tried reproducing the issue? If yes, steps to reproduce it would help immensely! For the issues mentioned, in order:

- Collapse chassis. Happens 100% of the time.
- Download Crew Manifest and open it. Happens 100% of the time.
- Send a message using any available means. Happens ~90% of the time.
* All additional details help. Such as round ID, an admin you talked to if the issue required immediate fixing, etcetera, etcetera. Literally every round in the last week.

**Comment by Asheram** [comment] 2019-04-03 04:58
Will confirm this and add that your saved settings (in character setup) doesn't get imported when you get the prompt that someone is requesting a pAI.

**Comment by Karolis2011** [comment] 2019-08-16 07:48
Only valid reported issue in this is chassis collapse.
Manifest part is Duplicate of #2124 
Chassis is Test & Todo for #6814
Digital messenger is not a bug.

**Comment by Geevies** [comment] 2020-03-31 18:57
I believe these were fixed, reopen if not.

**Closed by Geevies** 2020-03-31 18:57 UTC
