### ISSUE TITLE
Phasing through Windoors

### ISSUE THREAD

**Issue by UnknownMurders** [Aurorastation/Aurora.3#5044] opened 2018-07-24 06:01 UTC
https://i.gyazo.com/23be9c981b484e5dd259378425d778ab.mp4
I was able to phase through windoors by clicking on the table to put my experimental welding tool on the table, however I was not able to pick my experimental welding tool back from the table.

**Comment by SoundScopes** [comment] 2018-07-31 07:59
Duplicate of #4951

**Closed by SoundScopes** 2018-07-31 07:59 UTC
Labels: Duplicate
