### ISSUE TITLE
When taking out a full tile and putting it back it turns into the smaller version of the tiles.

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#14931] opened 2022-10-16 19:41 UTC
Happens every round.
Pretty sure that is not an indended feature.
Full tiles only exist when freshly crafted or when placed in map creation but turn into other type of tile when removed and placed back.

**Comment by SleepyGemmy** [comment] 2022-10-17 15:42
duplicate of #14658.

**Closed** 2022-10-18 18:54 UTC
Labels: Duplicate
