### ISSUE TITLE
Vampire dominate commands inconsistent in their displayed appearance to their victims.

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#2461] opened 2017-05-26 04:22 UTC
Lately there's been reports of an issue of normal crewmembers not seeing dominate commands. As such, vampires often to adminhelp exactly what command they gave to the specific crewmember, which ends up in us having to relay what was said to another player. 

I'm not sure if this is the classic BYOND issue, or if this is because vampires try to dominate people who walk off out of range. Merely hearsay if anything, but this complaint seems to happen every time it's a vampire round.

**Comment by skull132** [comment] 2017-05-26 23:25
Effectively a dupe of #586

Will probably seek into fixing by the end of dev cycle, won't have time otherwise.

**Closed** 2017-06-02 13:19 UTC
Labels: flag:duplicate
