### ISSUE TITLE
Borg sprites freezing

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#9576] opened 2020-08-02 10:57 UTC
As it says on the tin. Sometimes the borg maintenance hatch gets stuck open and like, nothing will fix it. Resetting doesn't, opening and closing it again says it does, but the sprite doesn't change.

Also, chat text gets stuck on them as well.

**Comment by mikomyazaki** [comment] 2020-08-02 13:04
Can't reproduce. Messed around with it for a while. 
It looks like handle_panel_overlay() will *always* update the icon, but according to this issue it is not.

Probably need some VVing when this is happening on the server to debug.

**Comment by Geevies** [comment] 2020-08-03 10:01
@mikomyazaki I've noticed the same with borg speech bubbles. I think sometimes overlays don't get cut properly in very rare occasions.

**Comment by StationCrab** [comment] 2020-08-05 04:58
> @mikomyazaki I've noticed the same with borg speech bubbles. I think sometimes overlays don't get cut properly in very rare occasions.

My bubble seems to get stuck when I use a speech macro right after posting something I typed out. The macro does "say !ping"

**Comment by Geevies** [comment] 2020-12-08 16:09
i think this got fixed by my borg overlay refactor

**Closed by Geevies** 2020-12-08 16:09 UTC
Labels: Bug Confirmed
