### ISSUE TITLE
Slipping bigger shoes over your sandals as wizard nullifies your powers as if you don't have the entire set.

### ISSUE THREAD

**Issue by Arzion5** [Aurorastation/Aurora.3#851] opened 2016-08-31 20:21 UTC

**Comment by MarinaGryphon** [comment] 2018-09-09 15:53
I believe this is intended and/or unavoidable. This will either be marked as "not a bug" or "won't fix", depending on which that is.
To be fair, if you're talking about magboots, it probably *could* be fixed, but for marginal gain. You could always just say that it interferes with the sandals' magical properties.

**Comment by Geevies** [comment] 2019-10-16 12:57
Shoes don't matter for wizard garb anymore, it seems.

**Closed by Geevies** 2019-10-16 12:57 UTC
