### ISSUE TITLE
Devouring creatures does not work with any abiotic items

### ISSUE THREAD

**Issue by YuriDaruski** [Aurorastation/Aurora.3#2253] opened 2017-05-14 00:04 UTC
Don't know if this will be a future problem, considering I have no idea how much Xeno stuff we'll do, but having /any/ abiotic item/body part labels the creature as inedible. Perhaps making them edible, but leaving behind a robo-part would work somehow? Either way, just labels them as "You cannot eat this creature" or something on those lines.

**Comment by Fire-and-Glory** [comment] 2017-05-14 00:19
Are you sure it was referring to prosthetic body parts?

In my experience, if the game mentions abiotic items then it actually means you can't do that while holding something in your hands, or the other guy is holding something in their hands.

**Comment by MarinaGryphon** [comment] 2017-05-14 01:37
I specifically got rid of my prosthetics for that character. I think you can't devour greater forms, actually.

~But hey. We vorestation now.~

**Comment by MarinaGryphon** [comment] 2017-05-14 01:38
Also, please note that it also didn't mention abiotic items. I only suggested that. At the time, I thought having clothes/an id/a pda/stuff in my pockets/whatever may have been the issue.

**Comment by YuriDaruski** [comment] 2017-05-14 06:26
Aye, just assumed, that perhaps you had biotic eyes or something. But she did say she was just a normal human. The only thing I can think of is maybe the sentinel's belly was already too full of a skrell but again, unsure. Biosuit was removed and character was on the floor, voiding any held items.

**Comment by Alberyk** [comment] 2017-05-14 06:36
Aliens can't devour people, that is an issue caused by nanako's rework of devouring.

**Comment by Lohikar** [comment] 2017-09-05 05:41
Fixed by #3231.

**Closed by Lohikar** 2017-09-05 05:41 UTC
