### ISSUE TITLE
Odin spawns and duplicates.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#3799] opened 2017-11-02 16:59 UTC
Seems if you spawn on the Odin as Captain or CMO and possibly other head roles, you will spawn in full gear, and all your belongings will be duplicated upon entering the shuttle.

**Comment by SoundScopes** [comment] 2017-11-02 19:37
Related, most likely duplicate of #3165

**Closed** 2020-12-05 13:14 UTC
Labels: Cannot Replicate
