### ISSUE TITLE
Vending machines break for the entire server/ UI breaking issue.

### ISSUE THREAD

**Issue by Spoopy11** [Aurorastation/Aurora.3#5181] opened 2018-08-25 20:39 UTC
This is happening very, very commonly since the big update I believe, though if you need a specific id:  bV2-dasw

Essentially at a random point during the round vending machine buttons will entirely stop functioning. E,G, if I click on a food item in a food vending machine, it does not progress to payment. If you use a vending machine which dispenses items for free, this is also the same.

I think I heard murmurs that this might also be the case for anything else that uses NanoUI.

This is pretty devastating since chem fridges, veg fridges, seed dispensers entirely break which can grind some department to a halt.

**Comment by Alberyk** [comment] 2018-08-25 20:42
Duplicate of #5038.

**Closed by Alberyk** 2018-08-25 20:42 UTC
