### ISSUE TITLE
Certain floor tiles can't be put down

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#9541] opened 2020-07-31 11:56 UTC
Silver, Gold and Uranium Floor tiles can't be placed down. Nothing happens when you try.

Diamond floor tiles are meant to make four, but instantly place the tile down on the tile you're standing on, even if it has a floor tile already. Also Diamond floors break reality somehow.

https://gyazo.com/a63c9b7f404e49b3450bf4cdef199561

**Comment by Doxxmedearly** [comment] 2020-07-31 15:04
Duplicate of #5734 and #5498

.... which means we really should figure this out.

**Closed** 2020-07-31 23:50 UTC
Labels: Duplicate
