### ISSUE TITLE
Radiation leaks through Radiation Suits

### ISSUE THREAD

**Issue by furrycactus** [Aurorastation/Aurora.3#8205] opened 2020-02-06 11:10 UTC
When firing the emitter at the Supermatter crystal, radiation still irradiates you even if you're wearing a full radiation suit.

**Comment by mikomyazaki** [comment] 2020-02-20 00:10
Could not reproduce.

Put on a radiation suit and hat and stood inside the SM chamber directly next to the SM crystal while it was on for a few ticks, did not take any radiation damage.

**Comment by Talkarcabbage** [comment] 2020-02-20 20:47
I think this has been addressed by #8290 (about 4 days ago from this post)
Radiation protection works on an armor stat basis. All radiation armor was being ignored if you were wearing gear that had no armor at all due to the power of null. 
Pretty sure it thus relied on whether or not you were wearing workboots (which have armor/rad armor), vs other types of shoes, basically.

**Closed** 2020-03-16 14:08 UTC
