### ISSUE TITLE
Pepperspray Grenade gas passes through doors and windows which block air.

### ISSUE THREAD

**Issue by honkel** [Aurorastation/Aurora.3#14158] opened 2022-05-31 18:18 UTC
Specifically the door and window of the Brig next to the Warden's office leading into communal. The gas reach two tiles past the fully closed door and intact window. This may apply to other gases as well, I have not tested.

EDIT: The gas also has a 100% heart failure from shock rate on humans and incapacitated a Unathi severely for several minutes. It seems far too powerful.

EDIT2: 115 unites of capsaicin was found in the stomach of someone who had heart failure from shock about two minutes after being peppersprayed.

**Comment by SleepyGemmy** [comment] 2022-05-31 18:28
technically a duplicate of #4210.

**Comment by FluffyGhoster** [comment] 2023-09-10 07:30
I think this was fixed around the end of last year (2022), if not, feel free to reopen

**Closed by FluffyGhoster** 2023-09-10 07:30 UTC
