### ISSUE TITLE
Cargo crates in warehouse can spawn items that aren't intended to be in-game

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1131] opened 2016-11-07 05:00 UTC
As an example, in GameID bk84Xf, 'Gloves' were spawned which, as per what @Alberyk told me, were the 'parent/'group' gloves container, whatever you'd call it, that serves as the base for all gloves that are actually used in game. Said gloves had no sprite and I don't believe are actually usable.

**Comment by Alberyk** [comment] 2016-11-08 06:04
Same with it spawning poster without any info/the structure outside any wall:

![](https://i.gyazo.com/c36de9700f9b65a0bad1221bed7e0d56.png)

**Comment by EvilBrage** [comment] 2016-11-08 06:44
Not to mention it spawns traitor-only items such as the thermal imaging goggles which, I suspect, are not supposed to spawn.

**Comment by NanakoAC** [comment] 2016-11-08 06:50
@EvilBrage not a bug.

**Comment by NanakoAC** [comment] 2016-11-09 00:15
fixed in #1143

**Comment by skull132** [comment] 2016-11-09 22:14
Not entirely fixed, the exclusion lists still need more shit.

Another entry: any type of HUD glasses, as they are not ID locked and can be easily abused.

**Comment by Arrow768** [comment] 2016-11-11 21:24
Awaiting mere is to be used for pull requests that need merging.

**Comment by ShameOnTurtles** [comment] 2016-11-12 13:15
Game ID bK7mYf saw the syndicate hardsuit control module spawn. Mentioning this for knowledge of what needs to be excluded purposes.

**Comment by Alberyk** [comment] 2016-11-13 01:11
Things that are possible issues:
- augmentvision and thermals, both are pretty much thermal glasses.
- swords, they can block and deal around 40 of brute per hit
- ERT, crismon red hardsuit and stealth hardsuit.
- tacticool locker with swat armor

**Comment by Alberyk** [comment] 2016-11-13 23:56
Cargo can also spawn adminordrazine chem cartridges.

**Comment by Serveris** [comment] 2016-11-16 18:55
Cargo can spawn the Rapid Service Fabricator (RSF) device, which is a service cyborg loadout item.

**Comment by Serveris** [comment] 2016-11-18 21:57
Cargo can spawn a circuitboard to Central Command ID Modification consoles.

**Closed** 2016-12-22 01:15 UTC
Labels: bug:confirmed, flag:development
