### ISSUE TITLE
[Bug]: Can't put a noose on yourself or other conscious people.

### ISSUE THREAD

**Issue by LynxSolstice** [Aurorastation/Aurora.3#17943] opened 2023-12-12 23:05 UTC
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Whenever you try to put a noose on someone who isn't unconscious (yourself or someone else, it fails, every time.)

### Round ID

cre-dj1u

**Comment by FluffyGhoster** [comment] 2023-12-13 12:47
Duplicate of #17732

**Closed by FluffyGhoster** 2023-12-13 12:47 UTC
