### ISSUE TITLE
Armory Inventory

### ISSUE THREAD

**Issue by ben10083** [Aurorastation/Aurora.3#3406] opened 2017-09-06 20:55 UTC
Armory Inventory was bugged and I couldn't fill it out correctly. (see paper)
Also couldn't find armory inventory form on request console, it just wasn't there

Admin: TrickingTrapster

Round ID: bQk-ddWd

Paper: 

> [center][Large][b]NSS Exodus[/b][/large][br] [small]Armoury Inventory[/small][/center] [hr] [hr] [br] [b]Weaponry[/b][br] [field] Energy Gun(s)[br] [field] Laser Gun(s)[br] [field] Ion Rifle(s)[br] [field] Combat Shotgun(s) [hr] [b]Armour[/b][br] [field] Bulletproof Vest(s)[br] [field] Abalative Vest(s)[br] [field] Biohazard Suit(s)[br] [field] Bomb Suit(s) [hr] [b]Auxiliary Equipment[/b][br] [field] Gasmask(s)[br] [field] box(es) of Flashbangs[br] [field] box(es) of Handcuffs[br] [field] box(es) of R.O.B.U.S.T. Cartridges [hr] [b]Riot Equipment[/b][br] [field] Stun Baton(s)[br] [field] Riot Suit(s)[br] [field] Riot Shield(s) [hr] [b]Tactical Equipment[/b][br] [field] Tactical Armour(s)[br] [field] Tactical Helmet(s)[br] [field] Tactical Jumpsuit(s)[br] [field] Green Balaclava(s)[br] [field] Tactical HUD(s)[br] [field] Combat Belt(s)[br] [field] Black Glove(s)[br] [field] Jackboot(s) [hr] [b]Implants[/b][br] [field] Tracking Implant Box(es)[br] [field] Chemical Implant Box(es) [hr] [b]Defense Systems[/b][br] [field] Deployable Barrier(s)[br] [field] Portable Flasher(s) [hr] [b]Other[/b][br] [field] Holobadge Box(es) [hr] [b][center]Warden's's Signature:[/b] [field][/center] [hr]

**Comment by Lohikar** [comment] 2017-09-07 00:58
Duplicate of #2986.

**Closed by Lohikar** 2017-09-07 00:58 UTC
