### ISSUE TITLE
AI Examine Bug.

### ISSUE THREAD

**Issue by Muncorn** [Aurorastation/Aurora.3#2576] opened 2017-06-02 23:26 UTC
AI's are not meant to be able to examine objects for decently obvious reasons. However, I've found that using the Right-Click Menu to examine instead of shift click sometimes lets you examine normally, however certain items (Emergency Shutters in some cases, unsure overall) bring up an error report looking like this: https://gyazo.com/4d3d440dbf36a1e9f0965039a776016e
What causes this problem is out of my knowledge, but could be used for considerable meta if people know about it.

**Comment by LordFowl** [comment] 2017-06-03 00:32
"Decently obvious reasons" being? Whatever happened to the AI hotkey we had specifically for purpose of examine?

**Comment by Lohikar** [comment] 2017-06-03 00:34
AIs are supposed to be able to examine objects. The game doesn't consider the AI adjacent to the object, so it won't give extended info like you can get if you examine an object you're right beside.

The issue where examine does not work sometimes is a result of how the AI eye works & how BYOND handles verb visibility - it's not really in our control to fix.

**Comment by SoundScopes** [comment] 2017-06-26 15:32
Duplicate of #858

Sidenote the AI hotkeys were part of a cyborg/AI improvement code that apparently were never ported to current code

**Comment by MarinaGryphon** [comment] 2019-10-22 18:34
Duplicate, closed.

**Closed by MarinaGryphon** 2019-10-22 18:34 UTC
Labels: Won't Fix
