### ISSUE TITLE
Visitor Spawn Bug

### ISSUE THREAD

**Issue by SilverTalismen** [Aurorastation/Aurora.3#11945] opened 2021-05-23 01:00 UTC
So currently, spawning as a visitor with round start places you on the Odin with a PDA and ID, going through the autodrobe gives you another PDA and ID, duplicating them and meaning one needs to be deleted.

**Comment by Shadow-Quill** [comment] 2021-08-30 19:57
Duplicate of https://github.com/Aurorastation/Aurora.3/issues/11687

**Closed** 2021-09-29 05:03 UTC
