### ISSUE TITLE
Merchant shuttle's floor reset

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#6668] opened 2019-07-05 08:36 UTC
When you move the merchant shuttle between docks, any changes that you've made to the floors reset.

For example, I replaced the entire interior floor with wood, and after I moved to the station it changed back to metal plating.

Having an admin change the floor back to would appear to correct the issue on all of the tiles they fixed, but the ones that they missed continue to change back to metal plating with every shuttle relocation.

**Comment by Sindorman** [comment] 2019-07-06 17:42
That's all shuttles.
Will be fixed in #5771

**Comment by Sindorman** [comment] 2019-07-06 17:43
Duplicate of #6336

**Closed by Sindorman** 2019-07-06 17:43 UTC
Labels: Bug Confirmed
