### ISSUE TITLE
Newly embraced vampires are green forever.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#2039] opened 2017-04-02 07:26 UTC
Seems like once theyve fed enough and they de-frenzy, they're still green, and it doesnt go away, not over time or with Ryetalyn. There was plenty of time for it to do so, over an hour, if not more, but they remained unchanged.

**Comment by NanakoAC** [comment] 2017-04-02 16:34
this is caused by the frenzy state, and the icon only updates in certain conditions. I will fix it in due time. But a workaround for now:

Lying down and then standing up again should set the green overlay on or off, depending on whether you're in or out of frenzy mode appropriately

**Comment by JohnWildkins** [comment] 2020-12-05 13:02
fixed by #3524

**Closed by JohnWildkins** 2020-12-05 13:02 UTC
Labels: Bug Confirmed
