### ISSUE TITLE
When windoors lose power they turn invisible

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#14193] opened 2022-06-03 14:49 UTC
Title. Noticed in the medical bay after a blackout, all of the windoor sprites disappeared until they were interacted with.

**Comment by sheeplets** [comment] 2022-06-03 14:50
![image](https://user-images.githubusercontent.com/44004468/171878378-ede7e09e-78a8-44d8-9312-1a07dc50d6aa.png)

**Comment by SleepyGemmy** [comment] 2022-06-03 15:34
duplicate of #14037.

**Comment by Ben10083** [comment] 2022-06-03 18:02
Duplicate of #14037

**Closed** 2022-06-04 18:27 UTC
