### ISSUE TITLE
Cannot spawn with drop pouches

### ISSUE THREAD

**Issue by NebulaFlare** [Aurorastation/Aurora.3#2909] opened 2017-07-02 08:37 UTC
I had both the scarf selected and drop pouch selected to spawn. I spawned in with the scarf, (Dark blue scarf for clarification) but no drop pouches (medical for clarification). Both were selected to be spawned in, but only the scarf came in. The drop pouches were never loaded. Ever.

-Spawning at the start of the round does not include the drop pouch.
-Spawning after round starts (at NTCC) also does not include the drop pouch.
-Removing the scarf allows you to spawn with the drop pouch again.

**Comment by Lohikar** [comment] 2017-07-02 16:23
Duplicate of #2906.

**Closed by Lohikar** 2017-07-02 16:23 UTC
