### ISSUE TITLE
Flashers Set off by Wandering Spirits

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#1929] opened 2017-03-17 01:41 UTC
At first, I thought the issue was that portable flashes were going off wildly just by people being within 4 or so squares of them, even while stationary, but someone helpfully informed me that ghosts moving around in the armory were making them flash for kicks.  So, someone should fix that.  Ghosts setting off flashes constantly because they think it's funny is not helpful at all.

https://i.gyazo.com/47111c99d41b001eb27595ba11c95f10.mp4

**Comment by Lohikar** [comment] 2017-03-17 02:37
Duplicate of #1877.

**Closed** 2017-03-19 19:26 UTC
Labels: flag:duplicate
