### ISSUE TITLE
Xenoarcheology Flags become unstoreable.

### ISSUE THREAD

**Issue by SirFruitcakes** [Aurorastation/Aurora.3#2058] opened 2017-04-07 13:52 UTC
100% Reproduceable, just place a flag down, store it into the stack of same colored flags, and you can no longer place the stack into your backpack. Not sure about the cause, but it pretty much makes the flags useless.

**Comment by Lohikar** [comment] 2017-04-07 18:49
Duplicate of #1927.

**Closed by Lohikar** 2017-04-07 18:49 UTC
