### ISSUE TITLE
Walking away from a computer while using it to look through a camera does not make you exit the camera vision

### ISSUE THREAD

**Issue by mikomyazaki** [Aurorastation/Aurora.3#9779] opened 2020-08-25 11:28 UTC
In this image I am looking through the camera. You can see the UI greys out appropriately, but it does not reset my view to the mob.

![walk_away](https://user-images.githubusercontent.com/47489928/91169034-86f3d680-e6ce-11ea-89a9-9ab37a705d12.gif)

**Comment by JohnWildkins** [comment] 2020-12-06 15:08
duplicate of #10329

**Closed by JohnWildkins** 2020-12-06 15:08 UTC
