### ISSUE TITLE
AI Medical HUDs not working properly

### ISSUE THREAD

**Issue by CakeIsOssim** [Aurorastation/Aurora.3#81] opened 2016-02-09 04:10 UTC
The AI's medical sensor seems to just... dissappear randomly on random people, for no reason that I could discern.

**Comment by skull132** [comment] 2016-02-10 12:30
It actually works as intended. HealthHUDs no longer magically show the health of everyone forever: the amount of data sent is dependent on the suit sensor levels of the observed target. If they have them off, they will not show on HUDs at all. If they have them at Binary, you only get an icon indicating whether or not they're alive. Higher than binary, and you get the health bar as well.

Closing issue.

**Closed by skull132** 2016-02-10 12:30 UTC
Labels: Not A Bug
