### ISSUE TITLE
Character Preferences

### ISSUE THREAD

**Issue by ArcBotSS13** [Aurorastation/Aurora.3#382] opened 2016-06-05 12:39 UTC
So I noticed a bug with the new character preferences setup, also a little addition.

Starting with the bug: Basically, I have an IAA character I play a lot, and I noticed something odd in her setup, all the antagonist options were set to 'yes'. I never have any options set to yes on my IAA character, so checking a few things, I found out that when you switch antag options on another character of yours to 'yes' it switches it to yes for ALL of your characters. 

little addition: When you click "delete character" there should really be an interface popup saying "Are you sure you want to delete this character?" I accidentally deleted one of mine thinking it was one I don't play anymore. I already re-made it though so that's fine.

**Comment by skull132** [comment] 2016-06-05 13:51
Not a bug. Even on the old filesystem, antag preferences were saved under the user's own settings, and not attached to any characters. I carried on with that mentality as I developed the SQL based system.

As for the confirmation button, seems like a gooder idea. Though may warrant another issue report with an enhancement flag, as I'm closing this one.

**Closed** 2016-06-05 13:51 UTC
Labels: Not A Bug
