### ISSUE TITLE
Genetics for new map

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora.3#1817] opened 2017-02-21 07:27 UTC
Genetics needs to be updated/overhauled in preparation of the new map.

**Comment by NanakoAC** [comment] 2017-02-23 15:46
My plan for genetics is in a few parts:

1. Refactor of mutations to use the modifier system. Make them more robust, not inherently linked to genetics. And also simplify logic related to checking them, for performance improvements.

2. Refactor DNA modding to a more complex system involving mutations and disabilities overlapping on limited structural enzymes. Disabilities will be fragile and easy to gain, mutations will be harder and require precision

3. Implement organ printers, and re-examine organ decay and rejection

4. Map the actual facility. You'll probably be handling that as discussed

**Comment by NanakoAC** [comment] 2017-02-23 17:51
RE: Porting mutations to modifiers.

The way mutations currently work is that they're tied to gene datums. They have a proc for activating and deactivating, and they are hooked into many aspects of a mob's behaviour, like its life tick, speech, etc. In order that they can control and influence those behaviours.

The problem with this however, is that it makes mutations intrinsically tied to genetic modification. Which is not what we've been using them for. We have mutations that are applied by the wish granter, by various wizard and cult spells, by certain drugs and chemicals (especially alcohol) and by physical effects like taking damage. The issue is that all of these non genetic sources are not properly hooked into genetics, and don't get all the right procs. Resulting in inconsistencies in behaviour, and/or missing functionality depending on the source.

While making them hook up properly is possible, its the wrong direction to go. Your genetic code shouldnt be modified because you drank one pint too many.

I originally designed the modifier system as a generic and highly flexible means of making temporary changes to anything.  Its good for a lot of purposes, although the specific intent was for RPG-like status effects, buffs, powerups, etc. Mutations represent a lot of what those are. Theres a lot of overlap between the two in desired functionality. Rather than make competing systems with a lot of duplicate work, i felt it'd be best to instead rebuild mutations as an extension of the modifier system. It'll be a subclas with a significiant amoutn of unique stuff.

Problems and changes that will be part of the process:

1. Mutations and disabilities will use the same system. The distinction between them is largely semantic and genetics related
2. Mutations are generally being abstracted from genetics, and the system is being built to recognise multiple possible sources (including simultaneously) of a particular mutation or disability.  This will be handled by a bitflag that tracks the types of sources of a mutation (magical, genetic, tech, equipment, chemical, etc). Only when sources is zero will the mutation be removed.
3. Minor but significant, the mutations list will be a key-value dictionary, to greatly simplify lookups for specific mutations.  That said, where practical ill be phasing out checks for specific mutations (EG, hulk) in favour of instead checking abstracted values that mutation sets (a new Strength var)
4. This system will be the new model for most temporary effects that are currently used as a mutation. Eg blindness, deafness, mute, clumsy, confusion, etc. Its designed to cope well with short durations
5. Mutations will hook into all the same procs for life, say, etc that genes do. I have some ideas about using sublists to speed up these calls although it may be premature optimisation. EG, having a list of only mutations which care about when the host says something.

Anyways this is mostly 'under the hood' work that will be largely transparent to an end user. But it'll make things a lot easier for us to manage

**Comment by NanakoAC** [comment] 2017-02-23 20:02
RE: Refactoring DNA modding.

The plan is to have a certain amount of structural enzymes which is intentionally too small. Rather than the current system of one being made for each possible mutation or disability.

Instead, each mutation (disabilities are just a subtype of mutation now) will be associated with several structural enzymes each. Generally 1-5, depending on balance. This will result in a large degree of overlap.

For each structural enzyme associated with, each mutation will have an activation range. This is something like 200 points either side of a specific value (values of SE's range from 0-999)

Anyways, the key distinction:
In order to become active, a mutation must have all of its associated enzymes with values within the activation range.

In order to become active, a disability must have **any one** of its associated enzymes with values **outside** the activation range.

The starting set of structural enzymes will be a constructed value which ensures all disabilities are disabled. The  activation ranges of disabilities will always overlap so a perfect genome which doesnt have any of them is possible to construct. (and is the default for new mobs). Ill write an algorithm to build this linearly at roundstart

The activation ranges for (non disability) mutations will be assigned randomly, and are very likely to be outside the ranges for disabilities. In any particular round, it will almost certainly be impossible to collect all of the powers, and its extremely likely that most powers will conflict with some disability, resulting in you having to get both in order to have that mutation

This also means that randomly altering genes will result in lots of disabilities and few or no powers, necessitating a methodical and scientific approach

In addition to this, i plan to add some medicines and/or gene mods (which are locked behind research or rare material requirements) which can help with this process. Either increasing tolerance (widens the active ranges of mutations, increasing the chances of overlap) or adding redundancy, (allows a mutation to ignore the state of X number of enzymes (and treat them as active) when figuring out whether it should be active.)  Injecting these medicines into people has a significant chance of inducing mutations in itself.

Functions will exist for code to alter someone's SE's to give them a particular mutation, which will still be used by radstorms, genetic artifacts and unstable mutagen. These will trigger a mutation directly, by shifting all associated enzymes to within the tolerance range. But such things will no longer be "clean". Like with random modding, activating a specific mutation this way will likely induce disabilities, and maybe toggle the state of other mutations too. 

There will not be any way to cleanly give someone a specific **genetic** mutation. But as outlined above, mutations will no longer be strictly genetic, and its entirely possible to grant a mutation, with all associated privileges, without touching the genetic code


I plan to tie this system into upcoming metaresearch by awarding RMP for specific, measureable actions:

- One off reward for the first time in a round each mutation is induced (via genetic alteration only)
- Discovering associated enzymes and activation ranges for each mutation
- Passively for the mere existence of genetically altered humans. On the assumption they're probably contributing to science.


And lastly, i want to add a machine to genetics, the Protein Folder. This machine is basically just a glorified hint button. You'll insert a genetic sample, the machine will spend some time (5 mins ish) processing and burn a lot of power while doing so, and then spit out a couple of hints. Eg: "This mutation is associated with enzymes 5, 9 and 14".  

The protein folder Will primarily exist to provide some direction in the confusing and arcane complexity of this system, as well as providing a means of it being feasible to map out the human genome within the course of a round. Even with a hint machine, this will still be a daunting task

**Comment by skull132** [comment] 2017-06-18 11:39
With Nanako's departure, this is now RIP until we decide what to do with this.

**Closed by skull132** 2017-06-18 11:39 UTC
Labels: flag:development, flag:high priority, flag:mapping related
