### ISSUE TITLE
[New station] Lack of magboots for Xenoarch job

### ISSUE THREAD

**Issue by Coalf** [Aurorastation/Aurora.3#2782] opened 2017-06-21 18:31 UTC
Xenoarcheologists don't get any magboots, with the addition of Z levels and holes it's a pretty dangerous issue.
Here you go fowl happy?

**Comment by LordFowl** [comment] 2017-06-21 18:36
Not a bug.

**Comment by skull132** [comment] 2017-06-22 09:58
Can you also give them a porta-ladder, as they may need to ascend/descend in cases?

**Comment by LordFowl** [comment] 2017-06-22 15:03
Would be rather useless without a lookup verb. Placing down your portaladder randomly, hoping to get an ascenscion. @skull132

**Comment by skull132** [comment] 2017-06-22 16:10
Look up verb is in the plans for the next two weeks. I should actually badger Moondancer to get it 🤔

**Comment by Fire-and-Glory** [comment] 2017-06-23 08:53
Can't you just place the ladders down where you can see light shining on the ground? That's how I know where to go upwards as a miner with a jetpack.

**Comment by LordFowl** [comment] 2017-06-23 14:50
Light shines on the ground only in the theoretically rare instances that there is a chasm that leads all the way to the surface.

**Comment by Fire-and-Glory** [comment] 2017-06-25 03:17
They're not that rare, I can wander for a few seconds on the main level of the mine and find a chasm to the surface or three.

It's only really tricky when you're at the lowest level because then there are far less holes and little ground to see light on.

**Comment by Alberyk** [comment] 2017-06-26 16:57
Fixed in #2800

**Closed by Alberyk** 2017-06-26 16:57 UTC
