### ISSUE TITLE
Medical Bodyscanners won't print out scan reports.

### ISSUE THREAD

**Issue by Rickymadenson** [Aurorastation/Aurora.3#1473] opened 2017-01-08 18:17 UTC
So as medical main, I happened to stumble upon this after attempting numerous scans with patients. It's quite frustrating for surgeons to work without them as they're ICly considered mandatory to do surgery swiftly and to keep track on your patient's overall health. Pressing the print button won't allow anything to happen at all. You can still view their vitals luckily.

**Comment by skull132** [comment] 2017-01-08 18:19
Dupe of #1419

**Closed by skull132** 2017-01-08 18:19 UTC
Labels: flag:duplicate
