### ISSUE TITLE
Rollerbeds EAT voidsuits

### ISSUE THREAD

**Issue by SebkillerDK** [Aurorastation/Aurora.3#1632] opened 2017-01-23 21:33 UTC
as said in description. when you are buckled to a Medical rollerbed. and take your suit of. it vanishes.

**Comment by Alberyk** [comment] 2017-01-23 21:51
Duplicate of #1616

**Comment by LordFowl** [comment] 2017-01-23 21:52
Probably a duplicate of #1616

**Closed by Alberyk** 2017-01-23 21:52 UTC
