### ISSUE TITLE
[NEW MAP] Detective Office's Camera Console Does Not Work

### ISSUE THREAD

**Issue by Keinto** [Aurorastation/Aurora.3#2604] opened 2017-06-04 12:17 UTC
The console is set to the 'civilian east' network and cannot be changed to anything else nor can one check any of the cameras in that network.

**Comment by Arrow768** [comment] 2017-06-13 19:22
Replace it with a modular computer on security preset ?

**Comment by Lohikar** [comment] 2017-06-13 19:33
Wouldn't fix the core issue though.

**Comment by Alberyk** [comment] 2017-06-18 00:42
Tested and it seems to work just fine.

**Comment by Keinto** [comment] 2017-06-18 12:42
Yeah. I just played another round and it seems the issue was I was trying to use the console while buckled to the chair. I guess that's the bug?

**Comment by skull132** [comment] 2017-06-18 12:55
Duplicate of #2246

**Closed by skull132** 2017-06-18 12:55 UTC
Labels: flag:development, flag:mapping related
