### ISSUE TITLE
You can slip on wet floors while on a wheelchair

### ISSUE THREAD

**Issue by TheBimmer231** [Aurorastation/Aurora.3#928] opened 2016-09-14 04:54 UTC
i do not think someone can slip while using a wheel chair, please fix.

**Comment by NanakoAC** [comment] 2016-09-14 08:08
Duplicate of #342 

On a personal note, i've made some attempt to fix this bug and failed miserably. ill probably get it with enough time

**Closed** 2016-09-14 08:08 UTC
Labels: flag:duplicate
