### ISSUE TITLE
Medical anesthetic is not working correctly 

### ISSUE THREAD

**Issue by Moltenkore** [Aurorastation/Aurora.3#3095] opened 2017-07-18 04:59 UTC
Perhaps the pressure of the tanks is not set correctly in the operating rooms but everytime I go to use it on a patient they don't fall asleep and end up having to be chemically sedated.

**Comment by skull132** [comment] 2017-07-18 09:23
Round ID would have been useful. It's possible they also had a popped lung or something like that?

**Comment by skull132** [comment] 2017-07-18 10:34
Tested with medical tanks, works just fine. Has this happened to multiple different people? Option A is broken lungs. Option B is just empty tanks (after a round continued). Option C is a patient being a fucking mong and toggling their internals themselves after which they need to be beat violently so they never do that again.

**Comment by Moltenkore** [comment] 2017-07-18 18:33
One patient was me playing a M'sai Tajara, she just sat awake even though the tank was on and attached. She only had a broken leg.

Another was a human, same thing.. broken arm or leg and just sitting awake.

Finally another human, broken leg or foot when I was playing my CMO.

These was three different rounds, I don't remember the IDs.

**Comment by WizzardMaker** [comment] 2017-07-19 18:21
I had that problem yesterday too. In 3 out of 3 surgerys failed because of that. No lung problems, only broken bones.

**Comment by skull132** [comment] 2017-07-21 19:04
Time to do more testing.

**Comment by skull132** [comment] 2017-08-06 09:34
We have determined that Moltenkore was unaware of the fact that broken lungs deter anesthesia from working. Have broken lungs been the reason for other reports of this as well?

Alternatively, if you see new cases, make sure the lungs are not broken (not coughing up blood + clean body scan), and report back. I have a creeping suspicion that this is not a bug, and just oversight on the part of the medical players involved.

@Juani2400 @ariever @Pratepresidenten

**Comment by Moltenkore** [comment] 2017-08-06 09:55
@skull123 well no, I have been aware broken lungs do not accept anesthetic. It seems you misunderstood when I said that I was unaware that round's patient had broken lungs.

This bug still crops up though.

**Comment by Juani2400** [comment] 2017-08-06 12:38
As I said in my previous report, the patients I treated that day did not have any issues with their lungs, which eliminates this possibility. I have operated on quite a few since those times, and this issue happens on a 90% of the cases still.

**Comment by skull132** [comment] 2017-08-06 13:57
Whenever you see this, please ping me on Discord so I can drag my ass onto
the server and review some shit.

**Comment by XanderDox** [comment] 2018-03-12 17:58
Update for the sake of documentation.

This is still happening. It is not because of popped lungs - we are not utterly incompetent players within Medical. 

The majority of these incidents seem to occur when the operation is involving broken bones (I have also experienced it when having internal bleeding fixed), and I don't think I have had a surgery done on me in a long time that I did not, at some point, become conscious again. 

I will attempt to take screenshots of vitals and such the next time I experience this as a patient or surgeon.

**Comment by XanderDox** [comment] 2018-03-20 02:58
@skull132 If surgery anesthetic is the same gas that security's riot control thing uses (N20 I believe), then the waking up issue applies even to N20 leaks in the air.

After a few minutes of being asleep from it being in the air, you will wake up from anywhere between 3 to 10 seconds, before you pass back out. I have used this many times to get an airtank on fast enough to get out of the N20 cloud. Perhaps this could help you replicate the bug in a similar manner.

**Comment by JohnWildkins** [comment] 2020-12-07 06:50
Closing this as pre-brainmed. If this is still an issue, please file a new report.

**Closed by JohnWildkins** 2020-12-07 06:50 UTC
Labels: Cannot Replicate, Information Required
