### ISSUE TITLE
Anaesthetic is bugged.

### ISSUE THREAD

**Issue by Leudoberct1** [Aurorastation/Aurora.3#6527] opened 2019-06-03 16:16 UTC
Currently, if you activate someone's internals when they have a medical mask and anaesthetic tank on, they will go unconscious. But then, thirty seconds later, they wake up, and do not go back to sleep. This is happening even with a fresh tank that has not been used at all.

**Comment by JohnWildkins** [comment] 2020-12-06 13:39
duplicate of #3095

**Closed by JohnWildkins** 2020-12-06 13:39 UTC
