### ISSUE TITLE
Laptops able to be opened and closed at any distance.

### ISSUE THREAD

**Issue by bocmog** [Aurorastation/Aurora.3#4966] opened 2018-07-02 11:26 UTC
Found a laptop in disposals, alt clicking at any distance opened and closed it accordingly. Remote viewing through cameras returned the same result.

**Comment by Sindorman** [comment] 2018-07-02 21:09
This is a duplicated issue

**Comment by SoundScopes** [comment] 2018-07-03 17:23
Duplicate of #4697

**Closed by SoundScopes** 2018-07-03 17:23 UTC
Labels: Duplicate
