### ISSUE TITLE
AI UI bug when connecting with guest mode

### ISSUE THREAD

**Issue by HighAdmiral** [Aurorastation/Aurora.3#7968] opened 2020-01-09 20:42 UTC
The AI UI works fine when you initially connect, however if you have to restart your client for any reason, when you load back in all the onscreen buttons for the AI are gone.

**Comment by Karolis2011** [comment] 2020-01-11 20:27
Please be more specific.
If I didn't know of actually the issue, then I would have no idea what this is. Please always provide game IDs and context for such issues next time.

Now answer following question: did you login to server using external authentication?

**Comment by Karolis2011** [comment] 2020-01-11 20:31
Potential duplicate of #7895

**Comment by skull132** [comment] 2020-05-02 11:42
Dupe of #7895 . Closing.

**Closed by skull132** 2020-05-02 11:42 UTC
