### ISSUE TITLE
Autopsy Scanner Broken?

### ISSUE THREAD

**Issue by Surrealistik** [Aurorastation/Aurora.3#1862] opened 2017-03-02 02:22 UTC
Used the autopsy scanner on Jim Dang last night who was obviously exsanguinated by a vampire. 

Before doing so, I opened up all his body parts with a scalpel and scanned all of them; the only feedback I got was his time of death.

**Comment by CompleteGarbage** [comment] 2017-03-02 15:25
This is probably because vampire fangs aren't in the list of weapons that an autopsy scanner can pick up on-- changelings have the 'large organic needle' that shows up on autopsy, I don't believe  it wouldn't be too difficult to implement something similar for vampires.

**Comment by Surrealistik** [comment] 2017-03-04 04:44
Yeah, I'd think the fang marks would be pretty apparent. Please add.

**Comment by skull132** [comment] 2017-07-21 20:35
Not a bug, vamp fangs leave no trace. Might be addressed in a vampire update Soon:tm:

**Closed by skull132** 2017-07-21 20:35 UTC
Labels: flag:not a bug
