### ISSUE TITLE
Down in the floor + click your inventory item = bye

### ISSUE THREAD

**Issue by EthanMalakay** [Aurorastation/Aurora.3#2084] opened 2017-04-13 16:04 UTC
So lets say that you are in the floor, by any means, if you have gloves, for example, and click them while being in the ground, it will dissapear, but not its effects, when i had a cloaking device, i did click it from my pocket and it dissapeared from :world: but not its effects, so i keep being invisible, for the time that it emptied  its batery, so, bug.

Donw on the floor + click your ítem = goodbye to ítem.

**Comment by Lohikar** [comment] 2017-04-29 07:00
Duplicate of #1616.

**Closed by Lohikar** 2017-04-29 07:00 UTC
Labels: flag:duplicate
