### ISSUE TITLE
[Exodus] Ninja can not teleport on station Z-level

### ISSUE THREAD

**Issue by SonicGotNuked** [Aurorastation/Aurora.3#2639] opened 2017-06-07 02:27 UTC
I tried to teleport on station Z-level, could not. 
https://i.gyazo.com/a75ef3a420e5e2dcf418a6eedff85e84.png

**Comment by Synnono** [comment] 2017-06-09 17:06
This maybe has to do with ninja and antag stuff not working so great on Z1 by default?
_Thanks CentComm_

**Comment by skull132** [comment] 2017-06-09 17:19
Config option error. Will be fixed shortly.

Not a bug.

**Closed by skull132** 2017-06-09 17:19 UTC
Labels: flag:not a bug
