### ISSUE TITLE
Console interaction bug

### ISSUE THREAD

**Issue by Moonyman** [Aurorastation/Aurora.3#4526] opened 2018-04-04 16:35 UTC
You can't interface with a console somtimes. My guess would be it's because you're sitting on an immovable chair (specifically an armchair like a leather chair). Example is inability to interface with a camera console in the detective's office while sitting in the leather chair besides it. You also can't access PDA records presumably in the same conditions

**Comment by JohnWildkins** [comment] 2020-12-06 12:19
This, in turn, is a duplicate of #2246

**Closed by JohnWildkins** 2020-12-06 12:19 UTC
