### ISSUE TITLE
Robotech Deluxe in robotics shows all items as 'null'

### ISSUE THREAD

**Issue by soryy708** [Aurorastation/Aurora.3#4185] opened 2018-01-28 13:20 UTC
The Robotech Deluxe in robotics vends items, but all of the items are called 'null' in the menu.
If you click it, the item is vended correctly.
https://imgur.com/a/t9Drh

Game ID: bSE-cbmZ
Happened in two separate rounds.

**Comment by skull132** [comment] 2018-01-28 13:29
Duplicate of #4164

**Closed by skull132** 2018-01-28 13:29 UTC
