### ISSUE TITLE
Borg open hatch sprite sometimes sticks forever

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#10456] opened 2020-11-04 17:19 UTC
Game ID: b9X-csna

When borgs come in for upgrades, sometimes the open hatch sprite, and speech bubbles sometimes remain stuck. Ive tried a number of fixes, but generally it cant be fixed outside of replacing the entire borg.

The hatch sprite bug is not persistent, it doesnt always happen when you open a borg.

**Comment by JohnWildkins** [comment] 2020-12-06 09:21
duplicate of #9576

**Closed by JohnWildkins** 2020-12-06 09:21 UTC
