### ISSUE TITLE
Floor tiles destroyed on the Interpid stay destroyed when returning to the Horizon

### ISSUE THREAD

**Issue by connorjg1** [Aurorastation/Aurora.3#14291] opened 2022-06-11 04:25 UTC
If a floor tile is destroyed on the Intrepid by something like an explosion and then you return to the vessel it will delete the floor exposing it to open void. This is obviously unintentional as the hanger floor should still be there and not deleted by the damaged Intrepid.

**Comment by SleepyGemmy** [comment] 2022-06-11 16:44
related to #14151.
duplicate of #13935.

**Comment by connorjg1** [comment] 2022-06-12 00:27
> related to #14151.
> duplicate of #13935.

Closing as duplicate of #13935

**Closed** 2022-06-12 00:27 UTC
