### ISSUE TITLE
Camera Monitor Bug

### ISSUE THREAD

**Issue by WigglesworthJones** [Aurorastation/Aurora.3#5475] opened 2018-10-25 02:38 UTC
When buckled into a seat, all the buttons for the camera program don't seem to work. When unbuckled, it works fine.

**Comment by OneOneThreeEight** [comment] 2018-11-12 11:17
Don't believe there's a resolution for this, as this is a thing that's existed since the very beginning.

**Comment by JohnWildkins** [comment] 2020-12-06 12:18
Duplicate of #2246

**Closed by JohnWildkins** 2020-12-06 12:18 UTC
