### ISSUE TITLE
Vial of Venemum - has no initial effect

### ISSUE THREAD

**Issue by NerdyVampire** [Aurorastation/Aurora.3#10597] opened 2020-11-19 14:30 UTC
The vial of Venemum costs 4 TC's and is supposed to change you surgically for a time, giving you a new appearance (and name?). I chugged it three times, waited.. and waited.. nothing happened. 15 minutes or so later, it reverted me, since I had admin help to change instead.

Either it should be removed for not working, the description should be changed, or it should be fixed.

**Comment by sheeplets** [comment] 2020-11-19 22:23
You need to inject it.

**Comment by NerdyVampire** [comment] 2020-11-19 23:13
> You need to inject it.

It is not apparent from https://wiki.aurorastation.org/index.php?title=Uplink, I cannot easily check if it is apparent in-game, but it might be worth including a syringe and make it a box-set

**Comment by Doxxmedearly** [comment] 2021-05-14 17:07
Will see if the wiki can be updated, but it works as intended, so I am closing this.

**Closed by Doxxmedearly** 2021-05-14 17:07 UTC
