### ISSUE TITLE
[Bug]: Infinite Fortune Cookies

### ISSUE THREAD

**Issue by Stev-the-third** [Aurorastation/Aurora.3#17155] opened 2023-08-27 10:18 UTC
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

When a fortune cookie is eaten, it summons another fortune cookie beneath you. I think it's fair to assume that it's summoning a _fortune cookie_ when it is meant to be summoning a _fortune._ Additionally, deleting it with admin powers just summons the fortunes. 

### How to reproduce

Eat fortune cookie.
Check ground beneath you.

**Comment by SleepyGemmy** [comment] 2023-08-27 21:29
duplicate of #14546. please search before creating an issue.

**Closed** 2023-08-27 21:29 UTC
Labels: Duplicate Issue
