### ISSUE TITLE
[Bug]: A lot of pAI PDA programs lead to 'Interface  was not found' and softlocking it

### ISSUE THREAD

**Issue by Afya212** [Aurorastation/Aurora.3#16840] opened 2023-07-22 18:25 UTC
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Title

**Comment by Doxxmedearly** [comment] 2023-07-23 19:27
More details would help the issue get resolved. Which programs? Any screenshots of the error? What happens with the 'softlock?'

**Comment by Trusty-Mccoolguy** [comment] 2023-07-30 19:44
This typically occurs when using the version found on the top, rather than the bottom (where it has the pAI flashlight, for instance). There is a duplicate of them this way and instead of actually hitting for instance 'security HUD' you're hitting a duplicate above it that softlocks it. Here's a screenshot of what the softlock looks like.

![image](https://github.com/Aurorastation/Aurora.3/assets/20867711/5496e8fb-9e70-4450-9458-c694b13cb014)

**Comment by Trusty-Mccoolguy** [comment] 2023-07-30 19:46
I'll try to add a picture of the bugged duplicates next time I have my computer interface non-softlocked.

**Closed** 2024-01-19 13:23 UTC
