### ISSUE TITLE
Antagonist ban issues

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#1880] opened 2017-03-05 06:41 UTC
Antag banning someone doesn't work. Previously, antagonist banning supposedly worked in blacklisting individuals from the roundstart drafting, so regardless if they actually set preferences it wouldn't allow it.

For whatever reason after the recent bay merge, people who switch their preferences for antagonist types on despite being banned from antagonist are still capable of being drafted and thus chosen as any antagonist type... circumventing the ban altogether that was intended to keep them not playing antagonist roles. And apparently the blacklist that existed before either doesn't work or doesn't exist now.

**Comment by Lohikar** [comment] 2017-03-05 07:01
Duplicate of #1822.

**Closed by Lohikar** 2017-03-05 07:01 UTC
