### ISSUE TITLE
[Bug]: Observers can detach other observers following a mob

### ISSUE THREAD

**Issue by zagoon** [Aurorastation/Aurora.3#20091] opened 2024-10-21 22:56 UTC
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

If ghosts are following a player, and one of those ghosts uses double-click to move away or jump to another mob, all observers on the first mob will instantly cease observing that player (they will de-orbit and no longer follow them).

### How to reproduce

1. Have more than one player following someone
2. Double-click to jump elsewhere on the screen

**Comment by AlaunusLux** [comment] 2024-10-21 23:17
Caused by changes in #20083 (for visibility)

**Comment by FluffyGhoster** [comment] 2024-10-23 04:10
Should be fixed whenever we refresh the testmerge

**Comment by FluffyGhoster** [comment] 2024-10-25 02:57
Should be fixed from now on, reopen if not

**Closed by FluffyGhoster** 2024-10-25 02:57 UTC
