### ISSUE TITLE
Suit sensors are borked

### ISSUE THREAD

**Issue by Weer6** [Aurorastation/Aurora.3#2018] opened 2017-03-30 22:31 UTC
Two things, first the sensor "map" shows blank space and no markers for anyone, likely because the Z-levels are somehow implemented into it. second, on the actual map, it reports a third number which is "undefined".

how to reproduce

1. Get suit sensors laptop
2. open.
3. Notice how there is a third "number for every coordinate, all undefined.
4 switch to map
5. be utterly disappointed by the lack of map.

**Comment by LordFowl** [comment] 2017-03-31 00:45
Does this apply to the current code, or new map code?

**Comment by Lohikar** [comment] 2017-03-31 00:59
Appears to be current, getting template errors when I open suit monitoring on a modular computer.

**Comment by SierraKomodo** [comment] 2017-03-31 21:51
Seems to work fine for the AI's suit sensors subsystem on current code.

**Comment by Arrow768** [comment] 2017-04-01 15:21
Unable to reproduce. It works fine on current.
![2017-04-01_172036](https://cloud.githubusercontent.com/assets/1331699/24579934/94296f4c-16ff-11e7-933b-c229dafa9c3f.jpg)

**Comment by skull132** [comment] 2017-07-21 20:33
Cannot replicate, no new info, no new reports. Invalid, closing.

**Closed by skull132** 2017-07-21 20:33 UTC
Labels: bug:cannot replicate
