### ISSUE TITLE
[new map] Holes are pretty much invisible and super deadly

### ISSUE THREAD

**Issue by gdudding** [Aurorastation/Aurora.3#2748] opened 2017-06-18 02:08 UTC
So, you can't really see the holes very well, and if you fall into them, it pretty much ends your round (it literally killed me because I landed on my head).

Other times, I've seen people trapped in the hole for the duration of their round.

The complaints about this are numerous, and we are told to come and complain about it on github.

Here I am.  I think the amount of damage taken from a fall is ridiculous, considering the hidden nature of the holes.

yep, I know there are ways to prevent falling.  Sometimes you don't have those (raiders, etc) or you just don't know (nothing informs you).  

There's nothing else in SS13 that instantly ruins your round that you couldn't have at least seen first, or that didn't have to be engineered by another player (like a bomb, etc), that doesn't have a multitude of ways of surviving/escaping.

This is not a fun feature.  

The holes should be:
A) Less Deadly.
B) Escapable by normal means without super specialized equipment.
C) Highly visible, even in low light
or
D) Removed entirely, because they add nothing to the game.

Another way to think about this, is that they are essentially no different than placing very hard to see landmines around the station, and telling people they have to wear special shoes to avoid stepping on landmines.  

What's the point?

Please fix this issue or tone it down.  

If this isn't the right place...  tell Aboshehab to stop sending people here with feature complaints.

**Comment by skull132** [comment] 2017-06-18 12:20
A few things.

### Visibility
First, regarding visibility. I really don't think they're that hard to spot. Examples:
https://kama.skullnet.me/index.php/s/gaEaUg1vMeySZVG
https://kama.skullnet.me/index.php/s/lN3CV9JhkCZHtxg
https://kama.skullnet.me/index.php/s/BGpvacbLYd0EW2Z

Even edge cases like this one are distinguishable if you start looking out for them:
https://kama.skullnet.me/index.php/s/ywPERY1Jv40vzUu
https://kama.skullnet.me/index.php/s/dRClf3RTpeG5Uax

If you know you're in an area where you risk falling into holes, you should simply make sure you have proper lights (literally a zippo will do, as demonstrated by last picture), and slightly adjust your movement. Unless you can provide me clear examples of situations where holes _are_ impossible to see, I'm inclined to think that this point is moot.

### Deadliness
That remains to be seen. I have reason to believe that the amount of people who fall victim to holes (gedit) will lower the more people familiarize themselves with it. So if a nerf towards the damage done is to be implemented, it'll probably be implemented post release at this point.

In my opinion, they should remain a hazard, not an inconvenience.

### Traversal
The lack of traversal means is primarily a thing with them being new. We've already added quite a few means to handle the holes, and have made sure all jobs who come into contact with open turf on a regular basis (miners, engineers, EMT) have the tools to handle them. Only case we've overlooked that I can think of are xenoarchs, who should probably be handed a few porta-ladders and magbooties.

Everyone else is not expected to run into holes unless in case of emergencies. And for emergencies, there is emergency equipment that's dispersed throughout the station (emergency ladders for now, but hoists will also arrive once they get out of review-needed hell). Once again, distribution rates will most likely have to be increased, but that's minor.

Since the end goal is to make all jobs relating to open turf have the equipment to handle them, and since we've already mostly covered this, I do not see a need to make them escapeable without specific equipment. Once again, they're meant to be a hazard, not an inconvenience.

### The Point
What is _the point_ of open turf? Well, two fold. First, they're required for a MultiZ station to actually be _meaningful._ Seriously, there's no point in having a multistory station if we're not using the fact that air, people, and _stuff_ can travel between the various levels in a vertical capacity.

Secondly, they're a good hazard for asteroid workers that do not require taking a page out of TG's book. TG's book would be monsters. Which don't jive well with HRP. They're a neat natural hazard which punish you if you do not pay attention, either by forgetting your equipment, not knowing your equipment, or by falling inside. They also provide an extension to the EMT job, with them being outfitted for handling open turf rescue in the current iteration of the development build.

In line with point two, and as I already stated, most people will not run into holes unless the situation is already FUBAR. At which point, dying from falling just becomes _another_ way to die in this game if you're not prepared. And the final half of that sentence is key: most instadeath hazards in SS13 (atmos, airflow, etcetera) can be avoided if you are properly equipped. And this equipment doesn't always have to be readily available. Open turf falls very neatly into this category.

**Comment by Arrow768** [comment] 2017-06-18 12:31
I should also note that yesterday we had 6 people fall into the crusher in a single shift.
After the first one fell down, there was a announcement.
After the second one fell down, there was another announcement.
Then someone fell down into the active crusher and got crushed.
This is when a engineer arrived and wanted to show how to use a jetpack to avoid falling down.
They forgot to fill the jetpack and enable it before walking over the edge and fell down.
Then two more people fell down (I dont know the exact circumstances)

The crusher pit is clearly visible.
There are warning signs placed.
And there have been multiple announcements by the AI and command about the dangers of the crusher the lift and open holes in general.

As shown by this example, it will still take a bit until people are aware of the dangers surrounding open holes.
4 test weekends are just not enough.
I imagine once the new map is regularly played for a few weeks the number of people falling down open holes will drop.

**Comment by MarinaGryphon** [comment] 2017-06-18 13:02
They are very easy to see.

**Comment by skull132** [comment] 2017-06-18 16:02
> I imagine once the new map is regularly played for a few weeks the number of people falling down open holes will drop.

It's already dropped, tbh.

**Comment by gdudding** [comment] 2017-06-18 19:45
**Regarding visibility - 3 things...**

The most important thing here is that THIS IS NOT HOW THEY APPEAR to people.  There was no situation in which I would have walked into these holes twice now.  Something is wrong, and that's why you're getting so many people falling into the holes.  In both cases I had a helmet light and clear view of the ground I was walking on, and then suddenly I had fallen down a hole with no warning...  as if I had been teleported.  

I originally thought that the holes were something that could just open up underneath you without warning because there was no visible hole that I fell into.  Multiple other people have said this is the same for them, that the holes are not appearing before they fall into them.  

The OTHER thing about visibility is that this goes against the behavior of the visibility of space tiles in other situations within SS13.  Normally you can jump and float across space tiles.  People understand this and probably fall in trying it when they are lucky enough for the hole to actually render on their screen.

Thirdly, if I can see SPACE down through a hole, then it would indicate that I can fall through the asteroid, safely into space.  It just doesn't make any kind of rational sense.

Further, you have to remember there is lag involved and other factors, where sometimes people move an extra few tiles that they didn't want to, just because of a spike in lag (or someone set off a bomb elsewhere, etc whatever).  You really think it's good gameplay that a 3 second spike in lag results in a (probably) round-ending experience for people (holes or crusher or otherwise)?  Yeah, there are a few cases in SS13 where that was the case before, but why add a bunch more of that, which no one ever asked for?  It's just weird.


**Realism**
Let's talk about realism for a second, at a couple of angles (I don't really intend to revisit this thread, so I'll be thorough - the attitude pushback in game and here when trying to give feedback makes me not really give a shit, tbh).  

If there were super deadly holes that multiple people literally died in on a given single 2 hour shift of a workplace, those holes would be HEAVILY ADDRESSED by signage and audible warning.  There would be AMPLE equipment for anyone expected to traverse it.  Jetpacks for everyone!  Signage, both on the asteroid and off...  and there should **be a memorial for the 69,300 workers who fell in the holes and died while constructing the station**.

There should be ropes, ladders, etc stored all over the place and easily stashable on a belt or backpack.  

Magboots should NOT even help you.  The ground is clearly not magnetic, this is goofy.  

If these holes are MEANT to be "highly visible" then in order to protect from lag, it should be harder to accidentally step into the hole.  My character would have an issue stepping over the ledge to begin with, and not just walk off the ledge like an automaton.

Every hole is a 9 meter drop?  There are no slopes?  How are we to determine where we can get back out of the hole if we can't look up?  

Honestly, the holes would be fine if they didn't ruin your round based on stepping on one tile (often invisible regardless of what you guys say, people are falling unexpected either due to lag or a rendering error on their screen, I was being as careful as I could).  

How many things in SS13 ruin your round because of accidentally stepping on one tile that wasn't behind an airlock or the result of a bomb or something?  There just aren't that many.


Anyway, it's whatever, good luck with it.  You really should look into the visibility of the holes thing at the very least because I'm telling you, there was no hole on my screen either of the times I fell into a hole and died.  It was all sand both times.

**Comment by Lohikar** [comment] 2017-06-18 20:07
If the holes are not drawing properly, make sure you have _at least_ BYOND 510; they are unlikely to draw correctly on older versions of BYOND.

**Comment by skull132** [comment] 2017-06-18 20:18
> I don't really intend to revisit this thread, so I'll be thorough - the attitude pushback in game and here when trying to give feedback makes me not really give a shit, tbh

Well okay. I spent a good amount of time explaining in detail and in a calm, articulated manner as to how holes work, why they work that way, and what we plan to do with them. But if your choice is to discard this feedback and to simply parrot, "My way or the highway!" without providing anything further constructive, then I fear we have little else to discuss here.

The three main points I could discern from your second reply are these:
* > I cannot see holes.

**As I stated clearly**, this is not by design. **As I requested clearly**, I need tangible evidence of this to act on it. Simply stating, "It's not working this way!" does little to give us what we need to fix this. I told you how they are designed to work, anything that goes counter to this is thus an implementation issue. So please, for the second time, make an issue report containing pictures of the error, and we will thus investigate. Until such a time, any complaint about this matter is not actionable and thus useless.
* > New things are bad because we're already used to something else!

Well, you can relearn. People will learn, over time, how to recognize holes, where the default spawned holes are, and how to be careful with them. If you are discouraged by changes which add more ways to die quickly, then I apologize, but there is little we can do about it.
* > Realism

This is a 2d farty spaceman game. Seriously. Ontop of that, your complaints are invalid when we consider what is already in the game. Magboots work on the asteroid, this is a fact established by the Exodus map. If you must have a scientific reasoning, it's due to the metallic composition of the soil or some such. (Plus, all holes **inside the station** are clearly marked with catwalks, hazard markers on the walls and floor, ladders, etcetera.)

Yes, every hole is indeed a large drop. This is consistently displayed by our mechanics. Climbing up takes time, even with ladders or gear, falling down deals damage, etcetera. Etcetera. These things are mechanically consistent, believe it or not.

You're also ignorant of other SS13 mechanics. There is no, "Click a button and get a spacesuit!" mechanic for dealing with hull breaches. You either find one, get given one, or you die. If you get stuck in a venting room without one, you will most likely die despite attempts to escape. Holes aren't even instadeath, there's a moderate to high chance of survival after a drop, you'll simply be out of commission for a long while (until you get help). Fun fact: this is similar to lack of breathable atmosphere, you have a short survival window.


Anyways. As this is not actionable and not really constructive, I'll now be closing the issue. If you do see holes render improperly, please submit a new issue report with screenshots as evidence. Along with your BYOND version and a note of whether or not you have a GPU.

**Closed by skull132** 2017-06-18 20:18 UTC
