### ISSUE TITLE
Wristwatches display the wrong date

### ISSUE THREAD

**Issue by CakeIsOssim** [Aurorastation/Aurora.3#1561] opened 2017-01-14 12:42 UTC
"You check your watch, spotting a digital collection of numbers reading '09:43'. Today's date is 'January 13. 2561'."

The proper date should be 2459.

**Comment by skull132** [comment] 2017-01-14 12:46
Duplicate of #1516

**Closed by skull132** 2017-01-14 12:46 UTC
Labels: flag:duplicate

**Comment by CakeIsOssim** [comment] 2017-01-14 12:50
Funny, I searched to make sure it wasn't. oh well

**Comment by skull132** [comment] 2017-01-14 13:01
It's not an obvious duplicate. But since they call the same function to get the date, they're effectively duplicates. Not something you'd really know unless you knew the code.
