### ISSUE TITLE
All KA's do two tile mining

### ISSUE THREAD

**Issue by Deridin** [Aurorastation/Aurora.3#6367] opened 2019-04-29 06:31 UTC
After testing TONS of different KA specs, I've seen that the MOST you can get out of mining with KA's after the new changes is two tiles. This makes them utterly useless as mining tools.

We tested with all of the Meteor core/experimental core combos we could think of on both medium/tactical/heavy frames. They were all useless and mining only 2 tiles despite some of the AoE effects being HUGE. Them doing little to no damage at all in pressurized areas is fine, but not being able to mine with a tool literally designed to mine with is terrible.

**Comment by Deridin** [comment] 2019-04-29 07:17
We tested with all of the Meteor core/experimental core combos we could think of on both medium/tactical/heavy frames. They were all useless and mining only 2 tiles despite some of the AoE effects being HUGE. Them doing little to no damage at all in pressurized areas is fine, but not being able to mine with a tool literally designed to mine with is terrible.

**Comment by Sindorman** [comment] 2019-04-29 22:59
A duplicate of #6365, it is being solved in #6364

**Closed by Sindorman** 2019-04-29 22:59 UTC
Labels: Bug Confirmed, Duplicate
