### ISSUE TITLE
[Bug]: medical-scan-target works inconsistently

### ISSUE THREAD

**Issue by zagoon** [Aurorastation/Aurora.3#20089] opened 2024-10-21 00:03 UTC
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Medical-scan-target often doesn't work when you jump to a mob ("This isn't a scannable target"). Moving away (but remaining on the same screen) and jumping back onto them will fix it for a while, but it may break again later in the round.

This is generally agnostic of how you attempt to follow them (follow verb, crew manifest, double-clicking, chat, etc.)

Examples:

![scannable1](https://github.com/user-attachments/assets/0c19fcf8-5baa-4b3c-8dc8-c5c7df091483)

![scannable2](https://github.com/user-attachments/assets/19807c38-ce0d-4c21-9ac3-1ec2c4bad37b)

![scannable3](https://github.com/user-attachments/assets/659cf7c8-c5bf-40a0-a64d-5799f0fe8b86)

I scan Auil'suos, move away and observe somewhere else for a while, then come back and attempt to scan them again (unclear how long this takes to reproduce, but it did eventually break for all the previously scanned mobs above):

![scannable4](https://github.com/user-attachments/assets/fb1b3899-fc86-44b8-89ad-e34aab45b9bd)

![scannable5](https://github.com/user-attachments/assets/2c55c437-6bba-432b-9732-96d9c2bb518b)

### How to reproduce

If you jump to a mob immediately after ghosting, this bug may not trigger. Future jumps will likely trigger it. Recommend trying multiple mobs to proc it.

**Comment by AlaunusLux** [comment] 2024-10-21 23:17
Caused by changes in #20083 (for visibility)

**Comment by FluffyGhoster** [comment] 2024-10-23 04:09
Will be fixed whenever we refresh the testmerge

**Comment by FluffyGhoster** [comment] 2024-10-25 02:57
Should be fixed from now on, reopen if not

**Closed by FluffyGhoster** 2024-10-25 02:57 UTC
Labels: ✔️ Issue Replicable
