### ISSUE TITLE
pAIs cannot be set as join preferences

### ISSUE THREAD

**Issue by Serveris** [Aurorastation/Aurora.3#1580] opened 2017-01-15 18:34 UTC
Players are unable to configure a pAI preference.

Therefore, anyone that activates a pAI card and searches for a personality is unable to get one, due to players not receiving a notification due to not being considered candidates.

**Comment by skull132** [comment] 2017-01-15 18:35
Duplicate of #1520

**Closed by skull132** 2017-01-15 18:35 UTC
Labels: flag:duplicate
