### ISSUE TITLE
Mech pilots/passengers can't hear speech/see emotes at all

### ISSUE THREAD

**Issue by kyres1** [Aurorastation/Aurora.3#8820] opened 2020-05-06 23:20 UTC
Title. Kinda debilitating for mecha users, unfortunately.

**Comment by Alberyk** [comment] 2020-05-07 04:07
Likely caused by the byond version again.

**Comment by skull132** [comment] 2020-05-08 11:12
Dupe of #8821

**Closed by skull132** 2020-05-08 11:12 UTC
