### ISSUE TITLE
Main Science/Civilian Surface Powergrid does not work

### ISSUE THREAD

**Issue by Huenererschrecker** [Aurorastation/Aurora.3#5655] opened 2018-11-22 18:34 UTC
The Main Science and Civilian Surface powergrids appear to be wired incorrect. When set up, they still try to send power to the Master powergrid, which in turn tries to power those two powergrids, which causes an infinite loop. This doesn't cause any damage but it basicly means that those two grids can never be set up. 

My best guess on this is that both grids have a cable somewhere that connects back to the master grid instead of going through the substations. I have no idea where it could be however as I've searched IC for the problem a few times now.

**Comment by Huenererschrecker** [comment] 2018-11-23 17:57
The Medical Main grid seems to have the same problem.

**Comment by furrycactus** [comment] 2018-11-24 12:51
Uhhh. Could you describe what you mean in a little more depth? I've checked all these things on the map, and there's no stray cables connecting the substations to the main grid. You're remembering to disable the breaker boxes if you're trying to run the substations, right? Because if a breaker box is active, then you will have a connecting wire running under it; because that's it's purpose, it's a substation bypass. Disabling them removes the cable under them, so they're not connected, so power runs through the SMES instead.

**Comment by Huenererschrecker** [comment] 2018-11-25 19:01
Yes, I can. I've made some screenshots to show the problem a little better. 
https://i.gyazo.com/c56edcd1ae1502a0f2ef32d6eda66faa.png
This is the security subgrid when turned on (mostly as reference and to show that I know how to turn on the subgrids)
https://i.gyazo.com/fdaa61f5ec7f297227edea6292479811.png
Here is the input I now used for the medical main subgrid.
https://i.gyazo.com/7b81fb6f9d276b49fa980c0ade94a202.png
Here is the result. Please note the available power of 1250kw and the many many not-medical related APC that get powered from this grid.
https://i.gyazo.com/6839e9d68ddbd0f604f3a93e30a8c8bb.png
A comparison screenshot for when I now turn the bypass back on.
https://i.gyazo.com/1cb4225cb5116ab940f4854d08c402d2.png
The bypasses to complete the picture. 

I've not attached screenshots for the other two subgrids but it's basicly the same problem.

**Comment by Huenererschrecker** [comment] 2018-12-05 15:15
There have been some changes with this problem since the few mapchanges. The medical grid now works as intended. The substations also don't try to power each other anymore in a quasi endless loop. Instead, now the Research Grid, Construction Grid and Civilian Surface Grid seem to be the same. Here's one of the problematic powernets. 

https://i.gyazo.com/476b68289a5f2ee01561682fc5afec52.png
https://i.gyazo.com/ab588c63936e49778d4856224aea0fd4.png

Settings where that every bypass was deactivated, max input on SMES units and 50.000 output on most SMES units.

**Comment by Ornias1993** [comment] 2019-01-08 10:43
Duplicate of #5165

**Closed** 2019-01-14 08:55 UTC
