### ISSUE TITLE
[New Map] The Supermatter Engine Cooling Pipeloop Doesn't Cool

### ISSUE THREAD

**Issue by K0NFL1QT** [Aurorastation/Aurora.3#2698] opened 2017-06-12 18:52 UTC
The issue is caused clearly by the cooling pipes being on sand tiles and not space, or 'open space'. This leads to an eventual, inevitable and seemingly unstoppable delamination. I have confirmed that going out to space and digging out the sand tiles to open space lets them cool properly again.

**Comment by printer16** [comment] 2017-06-12 18:54
Duplicate of #2533

**Comment by Arrow768** [comment] 2017-06-12 20:21
Closed as duplicate.

**Closed by Arrow768** 2017-06-12 20:21 UTC
Labels: flag:duplicate
