### ISSUE TITLE
[NEW MAP] Anesthetic tanks don't work properly

### ISSUE THREAD

**Issue by ariever** [Aurorastation/Aurora.3#2229] opened 2017-05-13 19:42 UTC
((I JUST NOTICED I FUCKED UP)) Anesthetic tanks don't distribute anesthetic properly. I was doing surgery on someone with broken legs, and first, it tool a good thirty seconds for them to go under, and during the surgery they woke up again. It was like they had a burst lung, without any lung damage. Soporific seems to work, though, and I gave him that instead.

**Comment by ariever** [comment] 2017-05-13 19:45
((I JUST NOTICED I FUCKED UP)) Anesthetic tanks don't distribute anesthetic properly. I was doing surgery on someone with broken legs, and first, it tool a good thirty seconds for them to go under, and during the surgery they woke up again. It was like they had a burst lung, without any lung damage. Soporific seems to work, though, and I gave him that instead.

**Comment by LordFowl** [comment] 2017-05-13 19:46
Fill out the form properly.

**Comment by LordFowl** [comment] 2017-05-13 20:38
Probably not a new map bug? Uhh.

**Comment by Lohikar** [comment] 2017-05-13 23:18
I made changes to potable tanks' air fill in development, likely cause.

**Comment by skull132** [comment] 2017-07-21 20:29
Duplicate of #3095.

Closing this one as the newer one is assigned and has more information.

**Closed by skull132** 2017-07-21 20:29 UTC
Labels: flag:development, flag:feedback required
