### ISSUE TITLE
Ammo Duplication bug

### ISSUE THREAD

**Issue by BathSaltsAddict** [Aurorastation/Aurora.3#2712] opened 2017-06-14 02:51 UTC
The tactical vendor in the armory is capable of duplicating ammo. Put a partially or completely empty box of shotgun shells/.45 mag/9mm mag in the vendor, vend it again, and it'll come out completely full. Hopefully a feature, probably a bug.

**Comment by Alberyk** [comment] 2017-06-18 16:26
Duplicate of #1719

**Closed by Alberyk** 2017-06-18 16:26 UTC
