### ISSUE TITLE
[Bug]: Cybersuit Hardsuit Control Module, Access Denied when printed.

### ISSUE THREAD

**Issue by LynxSolstice** [Aurorastation/Aurora.3#17932] opened 2023-12-11 18:06 UTC
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

When creating a cybersuit hardsuit as a Machinist, non-antagonist, for an engineer, also non-antagonist, the suit gives me access denied, even though I just created it from scratch.

![image](https://github.com/Aurorastation/Aurora.3/assets/112824777/498b7fda-61a8-4e5a-b5ee-20084cd5857a)

### Round ID

crd-cy9k

**Comment by FluffyGhoster** [comment] 2023-12-11 19:07
Duplicate of #17893

**Closed by FluffyGhoster** 2023-12-11 19:07 UTC
