### ISSUE TITLE
Maintenance Drones Cannot Place Camera Assemblies

### ISSUE THREAD

**Issue by Aurum22** [Aurorastation/Aurora.3#728] opened 2016-08-11 21:03 UTC
After a drone grabs a camera assembly with the magnetic gripper, it cannot place it on a wall- it simply tries to push the wall every time with the message "You push the wall, but nothing happens." The camera remains in the gripper during this time and is not placed.

**Comment by SierraKomodo** [comment] 2016-08-12 11:11
Cameras aren't installed by placing them on a wall. You drop the camera assembly on the tile in front of the wall, then use a wrench on the assembly to attach it to the wall.

**Comment by skull132** [comment] 2016-08-12 11:12
https://wiki.baystation12.net/Guide_to_construction#Security_Camera

> Place the camera assembly on the **tile** where'd you like the camera to be.

Not wall. The tile. Not a bug, closing.

**Closed by skull132** 2016-08-12 11:12 UTC
Labels: flag:not a bug
