### ISSUE TITLE
Roles get reset every round when you choose the "thrall" option.

### ISSUE THREAD

**Issue by MatterL** [Aurorastation/Aurora.3#1770] opened 2017-02-13 06:40 UTC
I've tried this multiple times but anytime I select to thrall in the rolls options it ends up reset the next round. However when not set to on the roles save correctly and don't reset.

**Comment by Lohikar** [comment] 2017-02-13 07:27
Possibly cause of #1670.

**Comment by skull132** [comment] 2017-07-15 21:55
Dupe of #1670

**Closed by skull132** 2017-07-15 21:55 UTC
