### ISSUE TITLE
Disto loop bugs out

### ISSUE THREAD

**Issue by Huenererschrecker** [Aurorastation/Aurora.3#5715] opened 2018-12-06 22:32 UTC
I don't know what causes this but at random intervals the distro loop decided to not work anymore. At that point, it stops putting air out or taking in new air. This is a big problem if any breaches happen.

**Comment by BurgerLUA** [comment] 2018-12-06 23:55
I've noticed this a lot lately too and I'm wondering what the issue is. There are so many instances where I as a dionaea player suck the air out of areas that vents and whatnot.

**Comment by furrycactus** [comment] 2018-12-07 08:21
I thought I might've been imagining things, but I'm glad to see I'm not. I've also noticed that the scrubber loop can go an entire shift without having any waste gas in it, unless any gas is specifically pumped into it like by piping engine waste into it or something. It's like the scrubbers just aren't working.

**Comment by Huenererschrecker** [comment] 2018-12-07 09:19
The waste loop might not actually be a problem, I'm currently running under the assumption that the CO2 output of organisms is too slow for it to matter in any way for the waste loop. Specificly, I monitored an SSD librarian for half an hour in it's office, the only difference in pressure was that it got down by about 5pKa, which is nothing.

**Comment by JohnWildkins** [comment] 2020-12-06 12:54
Duplicate of #4744

**Closed by JohnWildkins** 2020-12-06 12:54 UTC
