### ISSUE TITLE
You can look through walls with a Photocamera

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#14019] opened 2022-05-19 20:07 UTC
Yeah uh, so I found this out on accident
maybe it only works on moving mapspaces like Elevators.

**Comment by deGurkin** [comment] 2022-05-19 20:07
![grafik](https://user-images.githubusercontent.com/30761807/169395702-74cee0df-4d06-4815-a1d8-13cdc11a83ae.png)

**Comment by SleepyGemmy** [comment] 2022-05-19 21:13
duplicate of #6749.

**Comment by deGurkin** [comment] 2022-05-19 22:34
Oh my I am sorry

**Comment by JohnWildkins** [comment] 2022-05-20 13:37
> Oh my I am sorry

no worries king, better to report a bug twice than not at all

**Closed by JohnWildkins** 2022-05-20 13:37 UTC
