### ISSUE TITLE
Being buckled to a chair makes the game think you're locked down, and vice versa

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1163] opened 2016-11-15 18:01 UTC
A borg that's buckled to a chair gets marked as 'Locked down' on a robotics control console. If a borg that's locked down gets buckled then unbuckled from a chair, it releases the lockdown.

**Comment by Bedshaped** [comment] 2016-11-17 01:38
Marked as high priority until tested.

**Comment by MarinaGryphon** [comment] 2017-04-04 23:07
The issue isn't (entirely) with bucking or borgs, it's with how the console checks if it's locked down. I can easily fix that.
Also, you CAN let locked down borgs move by unbuckling them while locked down. It'll also lock their charge until they're actually unlocked. Working on fixing that, too.

**Closed** 2017-04-08 14:32 UTC
Labels: flag:high priority
