### ISSUE TITLE
Lt. Columbo. semi-duplicates steak

### ISSUE THREAD

**Issue by Koekiegast** [Aurorastation/Aurora.3#4512] opened 2018-04-01 22:00 UTC
Game id: bTF-df1N, the one after april fools
I have fed Lt. Columbo. twice now, using cooked stake, and in both cases the hand that held the stake still had something invisible in it when the stake ran out, stake drops a plate on the ground under Lt. Columbo. when it runs out, and when i dropped that a steak apeared, well i coudn't feed it to Lt. Columbo.  again but it was still an item. It disapeared when i put in the brig delivery chute.

**Comment by Ratvar** [comment] 2018-04-04 12:05
It's not just dogs. You can feed any pet, any human, anyone who isn't you and get undeletable food. Tomato that you can squish over and over, kois that you can plant everywhere. Biiiiiiig abuse potencial, if comboed with xenobotany.

Those broken food things with no chemicals inside break biogenerators, guess grinders will also bork with them inside, et cetera.

Those fancy fake plants seem to disappear slooooowly, as time goes, or maybe admins were messingwith me.

**Comment by Alberyk** [comment] 2018-04-06 18:55
Duplicate of #4293

**Closed by Alberyk** 2018-04-06 18:55 UTC
