### ISSUE TITLE
Tajaran can't wear mangled black gloves.

### ISSUE THREAD

**Issue by Alberyk** [Aurorastation/Aurora.3#40] opened 2016-02-01 23:44 UTC
After using wirecutters on black gloves, my tajaran character was unable to wear them, not sure if the same happens to unathi and other gloves.

**Comment by skull132** [comment] 2016-02-02 17:28
Closed in lieu of #45 , as the issue is much broader.

**Closed by skull132** 2016-02-02 17:28 UTC
