### ISSUE TITLE
AI harddrive full, unable to delete file

### ISSUE THREAD

**Issue by NerdyVampire** [Aurorastation/Aurora.3#10779] opened 2020-12-10 23:12 UTC
Description:
I copied the content of the common server, from the telecomms server monitor.
I proceeded to create a new file in my AI computer.
I started an edit of the file and pasted the content in, with the intent to trim the data.
The laptop displayed an error that the harddrive was full. I was then able to exit the program, and return to the main interface. I was not able to view the files of the harddrive with the desire to delete the file again. I was able to stop the file program from the main interface, but once I did so the entire interface shut down. I was then unable to bring the computer interface up again, even after restarting the client.

Desired result:
A text-file in my AI harddrive for future printing to security or command.

Desired fix:
An overflowed harddrive should not disable the ability to delete the file causing it. If otherwise unfixable, delete the file when the error occurs.

**Comment by Shadow-Quill** [comment] 2021-08-30 20:32
Couldn't reproduce the 'unable to open interface' issue.
Maxed out IO is fixed by scrolling to the bottom of the text file and clicking the `Restart Program` button, which will discard all current changes to the file.

**Closed** 2023-09-08 19:07 UTC
Labels: ❌ Issue Unreplicable
