### ISSUE TITLE
[NBT] Two Lightbulbs in the bar are not on the same Grid

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#13300] opened 2022-03-01 18:00 UTC
happened two shifts in a row now so it is not bluespace fuckery.
![grafik](https://user-images.githubusercontent.com/30761807/156223253-35183d1c-b382-48e4-9462-65e4a999dc3c.png)

**Comment by mikomyazaki** [comment] 2022-03-04 03:37
Actually it is bluespace fuckery. They're randomized and you hit on the 1 in 9 chance of them being the same two shifts in a row, go buy a lottery ticket!

Imo they should probably be randomized by area, so all lights in one area can be the same, or set to some mood based on area type... but it's not a bug. So I'll close this.

**Closed by mikomyazaki** 2022-03-04 03:37 UTC
