### ISSUE TITLE
Anesthetics not working as intended

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#3134] opened 2017-07-22 16:01 UTC
As we've had a few rounds on newmap now, it has become somewhat of a glaring issue. Anesthetics seems to be a bit bugged, as patients keep waking up in the middle of surgery on a frequent basis. This does sometimes happen, but the amount of times its happened lately, its far too consistent to be freak accidents.

Something is most definately wrong with anesthetics.

**Comment by Alberyk** [comment] 2017-07-22 16:10
Duplicate of #3095

**Closed by Alberyk** 2017-07-22 16:10 UTC
