### ISSUE TITLE
[Bug]: Tajara disappear when buckled to pews

### ISSUE THREAD

**Issue by WilliamMurdoch** [Aurorastation/Aurora.3#17212] opened 2023-09-01 01:34 UTC
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Tajara, at the least, disappear after buckling to pews. This was noticeable by everyone else in the chapel, not just client-side. Unsure if it affects other aliens. Humans are unaffected.
![image](https://github.com/Aurorastation/Aurora.3/assets/31459154/efb1976c-3da8-463f-ae81-78994095f0c9)

### How to reproduce

1. Enter the chapel as a Tajara
2. Buckle to one of the pews
3. The character sprite disappears

### Round ID

cpz-dx4H

**Comment by FluffyGhoster** [comment] 2023-09-12 06:17
This might be a duplicate of #17326 , did this happen in the chapel?

**Closed** 2023-09-13 11:19 UTC
