### ISSUE TITLE
[NEWMAP] Power held by cables don't seem to save through Z-Levels.

### ISSUE THREAD

**Issue by verywhiterabit** [Aurorastation/Aurora.3#2377] opened 2017-05-21 15:03 UTC
If you multitool a cable you might see 2MW but after climbing down the ladder next to it and checking the same wire at a lower point it might read only 400KW. I'm not sure if there's some intentional loss when transferring Z-levels but I wasn't able to find any reason to it.

**Comment by skull132** [comment] 2017-05-21 15:04
Duplicate of #2345 .

**Closed by skull132** 2017-05-21 15:04 UTC
