### ISSUE TITLE
Missing disposals piping in the maintenance north of robotics

### ISSUE THREAD

**Issue by Moltenkore** [Aurorastation/Aurora.3#4203] opened 2018-01-29 00:44 UTC
A small stretch of disposals pipe is missing from the maintenance north of robotics.

![Reference image]( https://tzli.me/i/Sgrbm1fUnP )

**Comment by LordFowl** [comment] 2018-01-29 00:46
Duplicate of #4197

**Closed by LordFowl** 2018-01-29 00:46 UTC
