### ISSUE TITLE
[NEW MAP] Mine turfs sometimes lose their sprite

### ISSUE THREAD

**Issue by Moltenkore** [Aurorastation/Aurora.3#2346] opened 2017-05-20 22:23 UTC
If an explosion happens it leaves a black tile which when right clicked just shows up as sand, rods cannot be placed on top of so a lattice and floor are impossible to create.

**Comment by Lohikar** [comment] 2017-05-21 03:32
This is caused by an error in the icon smoothing engine. It is still possible to place lattices on the turfs by dropping an object on the tile and alt-clicking on it to bring up the Turf menu; the turf is now selectable at the top of the list.

**Comment by skull132** [comment] 2017-05-28 11:38
@Lohikar You touched smoothing. Is this fixed?

**Comment by Lohikar** [comment] 2017-05-28 17:48
Not fixed, haven't gotten around to investigating. Recent PR to smoothing only affected diagonal smoothing, which is not used by mine turfs.

**Comment by Moltenkore** [comment] 2017-05-28 19:02
A way to trigger this is making a decent sized explosion and then placing lattice on the sides of the remaining floor, the adjacent sand tiles will then lose their sprite.

**Comment by Lohikar** [comment] 2017-09-05 05:33
I'm *fairly* sure I've fixed this, closing.

**Closed by Lohikar** 2017-09-05 05:33 UTC
Labels: bug:confirmed, flag:development
