### ISSUE TITLE
[Bug]: CoC Ship's Gun refuses to fire on Asteroid

### ISSUE THREAD

**Issue by mynameasjeff** [Aurorastation/Aurora.3#16628] opened 2023-07-04 06:23 UTC
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Third party ship

### Describe the issue

The CoC's guns, even when fully loaded and has a valid calibration. Will refuse to fire on Asteroids and potentially other hazards.

### How to reproduce

I-spawn into CoC Ranger ship
II-use any targeting console aboard
III-spam the 'fire' button

### Round ID

coD-aKRg

**Comment by NonQueueingMatt** [comment] 2023-07-04 10:55
duplicate of another bug, fixed in next PR

**Closed by NonQueueingMatt** 2023-07-04 10:55 UTC
