### ISSUE TITLE
Chem Duping

### ISSUE THREAD

**Issue by Nikita4096** [Aurorastation/Aurora.3#15804] opened 2023-02-12 12:31 UTC
Round ID - cml-brI2
Admin - ckey: melariara
Reported by - ckey:Nikita256

You can duplicate chemicals in your blood by first taking a blood sample, from yourself, then injecting it in yourself. Easy to replicate, too powerful when used with dangerous chems or even nicotine

**Comment by Nikita4096** [comment] 2023-02-12 12:34
Looks like a variation of issue #11156, but easier to replicate

**Comment by FluffyGhoster** [comment] 2023-09-10 01:47
An update on how to reproduce it:

1. Inject yourself with 15u of inaprovaline
2. Take out 15u of your blood
3. Put it inside a beaker
4. Take the pipette, set it to 0.1, click to take the blood and click again to put it back in
5. You have now duplicated the content of the reagents in the blood

I suspect it has something to do with the `reagent_data` of `/datum/reagents` not being properly handled for blood, but additional dwelling will be needed (since the chemistry code is a mess) to figure out how everything fits in the big picture exactly.

**Comment by FluffyGhoster** [comment] 2024-10-16 23:31
This should be fixed, reopen if not

**Closed by FluffyGhoster** 2024-10-16 23:31 UTC
Labels: ✔️ Issue Replicable
