### ISSUE TITLE
Can not spawn with toeless jackboots

### ISSUE THREAD

**Issue by DeadLantern** [Aurorastation/Aurora.3#6562] opened 2019-06-11 05:25 UTC
Every time you select Toeless jackboots in the xenowear loadout menu, you do not spawn with it and it says you do not have toeless jackboots selected in the loadout (even when saved).

**Comment by Arrow768** [comment] 2019-07-13 18:22
Closing as duplicate of #6520.
If its a different issue, reopen with a copy of the error message you get.

**Closed by Arrow768** 2019-07-13 18:22 UTC
