### ISSUE TITLE
Photo Cameras See Through Walls

### ISSUE THREAD

**Issue by XanderDox** [Aurorastation/Aurora.3#8879] opened 2020-05-15 02:23 UTC
Taking a picture of a wall will cause you to also photograph the other side of the wall too. 

https://cdn.discordapp.com/attachments/506308729474514946/710640157790830592/unknown.png

**Comment by JohnWildkins** [comment] 2020-12-06 15:08
duplicate of #6749

**Closed by JohnWildkins** 2020-12-06 15:08 UTC
