### ISSUE TITLE
Lobby Screen is black, no join button.

### ISSUE THREAD

**Issue by Weer6** [Aurorastation/Aurora.3#1879] opened 2017-03-05 05:19 UTC
Steps to reproduce Issue

1. log onto Server

2.expect join/declare ready button

3. Disappointment.

http://i.imgur.com/NCvBx7h.png

Updating doesn't fix this. Other players besides myself are affected by this.  not every player, but a couple.

**Comment by Weer6** [comment] 2017-03-05 05:45
Appendum: When I cleared the cache, three files were un clearable even after quitting Byond. restarting the computer and then clearing the Cache does not work either. The Options and Messages tab does nto show any resources being downloaded.

**Comment by Lohikar** [comment] 2017-03-05 05:55
This affects me too.
Probably related to the server resource file recompile.

@skull132

**Comment by OneOneThreeEight** [comment] 2017-03-05 05:59
was also affected. I had to be placed into a simple mob in-game to actually get in and observe as staff.

**Comment by Weer6** [comment] 2017-03-05 06:05
I feel pride in discovering a game breaking bug.

**Comment by OneOneThreeEight** [comment] 2017-03-05 06:10
you were not the first.

**Comment by Weer6** [comment] 2017-03-05 17:07
I was the first to report it on Git.

**Comment by skull132** [comment] 2017-03-05 17:07
Unable to reproduce reliably + was fixed the next time around.

Will most likely remain WONTFIX forever.

**Comment by skull132** [comment] 2017-05-16 08:57
Bug clean-up bonanza May 2017. Wasn't replicated until now, is thus ded.

**Closed by skull132** 2017-05-16 08:57 UTC
Labels: bug:cannot replicate, bug:confirmed, bug:won't fix, flag:high priority
