### ISSUE TITLE
AI view crashing while jumping between z-levels

### ISSUE THREAD

**Issue by HetNeSS** [Aurorastation/Aurora.3#3126] opened 2017-07-21 11:38 UTC
Sometimes your game crashes as being an AI, while trying to jump to some of a crewmembers by clicking their name in the chat, or just clicking "move up", "move down" buttons at the IC tab.

**Comment by Arrow768** [comment] 2017-07-21 13:03
Duplicate of #2331

**Closed** 2017-07-21 13:10 UTC
Labels: flag:duplicate
