### ISSUE TITLE
[NEWMAP] Can't enter sleeper pods in medical

### ISSUE THREAD

**Issue by VikingPingvin** [Aurorastation/Aurora.3#2212] opened 2017-05-13 18:34 UTC
HoP. No right click menu to enter sleepers. Left click opens the sleeper interaction UI.

**Comment by Juani2400** [comment] 2017-05-15 17:45
Not related to the map. This has been happening for a while. You need to drag yourself into the sleeper.

**Comment by VikingPingvin** [comment] 2017-05-15 18:03
So...it is an intentional "feature" to remove the right click option?

**Comment by skull132** [comment] 2017-07-21 20:32
Baydevs were fucking idiots when removing right click interaction, but it's not a bug. Closing, possibly reimplementing at some point.

**Closed by skull132** 2017-07-21 20:32 UTC
Labels: flag:development, flag:feedback required, flag:not a bug
