### ISSUE TITLE
Space Lube Cannot be Removed

### ISSUE THREAD

**Issue by Aurum22** [Aurorastation/Aurora.3#615] opened 2016-07-20 15:55 UTC
When somebody lubes up a floor tile with space lube, it simply cannot be removed either through cleaning with space cleaner, a mop, or even removing the entire floor tile.

**Comment by NanakoAC** [comment] 2016-07-20 19:12
Is this related to the thing with spills not drying up?

Spacelube can't be directly removed as such, but that's by design, it should go away by itself after 80 seconds
I think mopping it up should be possible and its something i plan to implement in future, but right now at least, that isnt the expected behaviour

@skull132 is the spill drying bug fixed?

**Comment by skull132** [comment] 2016-07-20 20:33
@NanakoAC It was fixed with #425 . However, it appears that spacelubed floor (wet = 2) does not reset itself. Ergo, it is lubed forever?

**Comment by Bedshaped** [comment] 2016-07-23 13:30
It's definitely not drying up. Darn clowns....

**Comment by veraknocks** [comment] 2016-07-28 16:13
build a wall on it, removes it apparently.

**Comment by NanakoAC** [comment] 2016-09-18 18:02
fixed in #946  if it isnt already. ill make sure this works

**Closed** 2016-09-28 20:08 UTC
Labels: enhancement:refactor
