### ISSUE TITLE
Alarms can reveal SAT core camera

### ISSUE THREAD

**Issue by nicemoreoften** [Aurorastation/Aurora.3#6740] opened 2019-07-17 20:41 UTC
![image](https://user-images.githubusercontent.com/16868528/61410129-90d6c380-a898-11e9-820b-4edb6b5ad9d2.png)
Everything is working as intended, but it has the potential to become "Captain, what is that nuke in the vault if we don't have a nuke?" Round 2

**Comment by OneOneThreeEight** [comment] 2019-07-20 10:48
Won't fix, not directly anyway. That thing needs to be less obvious. Nuke sign's gotta go.

**Comment by Doxxmedearly** [comment] 2020-07-29 14:56
Closing since not a bug

**Closed by Doxxmedearly** 2020-07-29 14:56 UTC
Labels: Not a Bug
