### ISSUE TITLE
Armblades can be deactivated by disarm intent users.

### ISSUE THREAD

**Issue by MysteryofDarkness** [Aurorastation/Aurora.3#3324] opened 2017-08-22 02:00 UTC
Normal crewmembers are able to deactivate changeling armblades by disarming them, they shouldn't be disarmable because they are the changeling's arm.

**Comment by Alberyk** [comment] 2017-08-22 02:19
Duplicate of #3072

**Closed by Alberyk** 2017-08-22 02:19 UTC
