### ISSUE TITLE
Ships moving in space near Horizon acts incorrectly

### ISSUE THREAD

**Issue by Afya212** [Aurorastation/Aurora.3#15626] opened 2023-01-22 17:44 UTC
The Izharshan shuttle docked outside the Horizon in standalone space. It then moved to docked with the Horizon resulting in the location they were located being 'open space' to fall down instead of proper space. Once the ship undocked from the Horizon it also left reinforced floor along where it was parked.

![image](https://user-images.githubusercontent.com/54920261/213926884-d396a40e-2b4b-4b33-9387-b9394aba5833.png)

![image](https://user-images.githubusercontent.com/54920261/213931349-6f32bdbf-d5da-4127-9bb6-b848ade7f4f1.png)

**Comment by SleepyGemmy** [comment] 2023-01-22 21:12
duplicate of #14151.

**Closed by SleepyGemmy** 2023-01-22 21:12 UTC
