### ISSUE TITLE
[Bug]: Holodeck nullrod dupe

### ISSUE THREAD

**Issue by airlines7** [Aurorastation/Aurora.3#17412] opened 2023-09-23 03:36 UTC
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon, Event / Other

### Describe the issue

TL;DC
messed with the tribunal chapel, saw that I could reshaped the staff into something else.
Tried it and it became no longer holodeck item, aka I could bring it around outside the location.

### How to reproduce

1. Got to holodeck, set to Tribunal Chapel
2. Take Tribunal rod from the altar
3. Reshape with null rod reshape option

### Round ID

Steel on the Horizon Event 1, before cpW-aqIz

### Staff ckey

forgot, one did delete the dupe for me.

**Comment by SleepyGemmy** [comment] 2023-09-23 10:37
caused by the item not being fake. easily fixed by mapping in a replacement.

**Closed** 2023-11-01 17:44 UTC
