### ISSUE TITLE
Flags do not work as intended - Mining and Research Outpost

### ISSUE THREAD

**Issue by NebulaFlare** [Aurorastation/Aurora.3#2795] opened 2017-06-24 10:22 UTC
The flags that are available at the outposts are broken as follows:

Once a stack of flags is used in hand (clicking on it) to plant into the ground, they can no longer be placed inside a bag.

A workaround to this is to take a flag, plant it, knock it down, pick it up, then collect the remaining stack of flags into the flag that was knocked down. This will allow it to be placed back inside the bag.

Haven't actually tested mining's flags, but I'm pretty sure the same issue still applies.

**Comment by skull132** [comment] 2017-06-24 10:25
Duplicate of #1927

**Closed by skull132** 2017-06-24 10:25 UTC
Labels: flag:duplicate
