### ISSUE TITLE
Written papers have a blank sprite // [date] and [time] not added

### ISSUE THREAD

**Issue by Juani2400** [Aurorastation/Aurora.3#1454] opened 2017-01-08 01:22 UTC
Pretty much what the title says. Papers with written content on them have a blank sprite. Also, [date] and [time] are not working.

**Comment by Lohikar** [comment] 2017-01-08 01:52
Partial duplicate of #1433.

**Comment by Arrow768** [comment] 2017-01-08 18:55
Date / Time confirmed as broken

**Closed** 2017-01-08 22:44 UTC
Labels: bug:confirmed
